/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BRFARM;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Wattana
 */
public class BR01R029 extends javax.swing.JFrame {

    ClassGetReport cgr = new ClassGetReport();
    ClassListData cld = new ClassListData();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy", Locale.US);
    SimpleDateFormat sdf2 = new SimpleDateFormat("yyyyMMdd", Locale.US);

    /**
     * Launch the application.
     */
    public BR01R029() {
        initComponents();
        this.setTitle("BR01R029. Duck Health Report : " + BRLogin.vDuckBreed + " " + BRLogin.vDuckBreedDesc + " : " + BRLogin.vFarm + " " + BRLogin.vFarmDesc);
        jLabelCode9.setText("Duck Health Report " + BRLogin.vDuckBreed + " Farm");
        jcbStartHouse.setModel(new DefaultComboBoxModel(cld.GetResultHouseDesc(BRLogin.vFarm, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll).toArray()));
        jcbEndHouse.setModel(new DefaultComboBoxModel(cld.GetResultHouseDesc(BRLogin.vFarm, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll).toArray()));
        jXDateStart.setFormats(sdf);
        jXDateEnd.setFormats(sdf);
        jXDateStart.setDate(new Date());
        jXDateEnd.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelTransport4 = new javax.swing.JPanel();
        jLabelCode9 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabelFlockSTDate = new javax.swing.JLabel();
        jXDateStart = new org.jdesktop.swingx.JXDatePicker();
        jLabelFlockSTDate1 = new javax.swing.JLabel();
        jXDateEnd = new org.jdesktop.swingx.JXDatePicker();
        jcbStartHouse = new javax.swing.JComboBox();
        jcbEndHouse = new javax.swing.JComboBox();
        jLabelFlockSTDate2 = new javax.swing.JLabel();
        jLabelFlockSTDate3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MAS_MSTD. PS FARM STANDARD");
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bangkok Ranch Public Co .,Ltd.");

        jPanelTransport4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCode9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode9.setForeground(java.awt.Color.red);
        jLabelCode9.setText("Standard Farm");

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabelFlockSTDate.setText("Start Date :");

        jLabelFlockSTDate1.setText("To Date :");

        jcbStartHouse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select House" }));
        jcbStartHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStartHouseActionPerformed(evt);
            }
        });
        jcbStartHouse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbStartHouseKeyPressed(evt);
            }
        });

        jcbEndHouse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select House" }));
        jcbEndHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEndHouseActionPerformed(evt);
            }
        });
        jcbEndHouse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbEndHouseKeyPressed(evt);
            }
        });

        jLabelFlockSTDate2.setText("Start House :");

        jLabelFlockSTDate3.setText("End House :");

        javax.swing.GroupLayout jPanelTransport4Layout = new javax.swing.GroupLayout(jPanelTransport4);
        jPanelTransport4.setLayout(jPanelTransport4Layout);
        jPanelTransport4Layout.setHorizontalGroup(
            jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                .addComponent(jLabelCode9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFlockSTDate)
                    .addComponent(jLabelFlockSTDate1)
                    .addComponent(jLabelFlockSTDate2)
                    .addComponent(jLabelFlockSTDate3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTransport4Layout.createSequentialGroup()
                        .addComponent(btnPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jcbStartHouse, 0, 185, Short.MAX_VALUE)
                    .addComponent(jcbEndHouse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXDateStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXDateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109))
        );
        jPanelTransport4Layout.setVerticalGroup(
            jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                .addComponent(jLabelCode9)
                .addGap(26, 26, 26)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbStartHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFlockSTDate2))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbEndHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFlockSTDate3))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFlockSTDate)
                    .addComponent(jXDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFlockSTDate1)
                    .addComponent(jXDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(jButtonClose))
                .addGap(50, 50, 50))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTransport4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTransport4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        if ("Please Select : House".equals(jcbStartHouse.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "Please Select House");
            jcbStartHouse.requestFocusInWindow();
        } else if ("Please Select : House".equals(jcbEndHouse.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "Please Select House");
            jcbEndHouse.requestFocusInWindow();
        } else {
            String[] getStartHouse = jcbStartHouse.getSelectedItem().toString().split(":");
            String vStartHouse = getStartHouse[0].trim();
            String[] getEndHouse = jcbEndHouse.getSelectedItem().toString().split(":");
            String vEndHouse = getEndHouse[0].trim();
            btnPrint.enable(false);
            cgr.rBR01R029("BR01R029", BRLogin.vFarm, BRLogin.vDuckBreed, sdf2.format(jXDateStart.getDate()), sdf2.format(jXDateEnd.getDate()), vStartHouse, vEndHouse);
            btnPrint.enable(true);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jcbStartHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStartHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbStartHouseActionPerformed

    private void jcbStartHouseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbStartHouseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbStartHouseKeyPressed

    private void jcbEndHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEndHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEndHouseActionPerformed

    private void jcbEndHouseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbEndHouseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEndHouseKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BR01R029.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BR01R029.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BR01R029.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BR01R029.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BR01R029().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCode9;
    private javax.swing.JLabel jLabelFlockSTDate;
    private javax.swing.JLabel jLabelFlockSTDate1;
    private javax.swing.JLabel jLabelFlockSTDate2;
    private javax.swing.JLabel jLabelFlockSTDate3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelTransport4;
    private org.jdesktop.swingx.JXDatePicker jXDateEnd;
    private org.jdesktop.swingx.JXDatePicker jXDateStart;
    private javax.swing.JComboBox jcbEndHouse;
    private javax.swing.JComboBox jcbStartHouse;
    // End of variables declaration//GEN-END:variables
}
