/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BRFARM;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Wattana
 */
public class BR01R004_CM extends javax.swing.JFrame {

    ClassGetReport cgr = new ClassGetReport();
    ClassInsertData cid = new ClassInsertData();
    ClassListData cld = new ClassListData();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy", Locale.US);
    SimpleDateFormat sdf2 = new SimpleDateFormat("yyyyMMdd", Locale.US);
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    SimpleDateFormat sdf3 = new SimpleDateFormat("yyyy-MM-dd", Locale.US);

    /**
     * Launch the application.
     */
    public BR01R004_CM() {
        initComponents();
        this.setTitle("BR01R004. Weekly Report : " + BRLogin.vDuckBreed + " " + BRLogin.vDuckBreedDesc + " : " + BRLogin.vFarm + " " + BRLogin.vFarmDesc);
        jLabelCode9.setText("Weekly Report " + BRLogin.vDuckBreed + " Farm");
        jXDateStart.setFormats(sdf);
        jXDateEnd.setFormats(sdf);
        jXDateStart.setDate(new Date());
        jXDateEnd.setDate(new Date());
        jcbGiver.setModel(new DefaultComboBoxModel(cld.GetResultUserNonAppr(BRLogin.vFarm).toArray()));
        jcbApprove.setModel(new DefaultComboBoxModel(cld.GetResultUserAppr(BRLogin.vFarm).toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelTransport4 = new javax.swing.JPanel();
        jLabelCode9 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabelFlockSTDate = new javax.swing.JLabel();
        jXDateStart = new org.jdesktop.swingx.JXDatePicker();
        jLabelFlockSTDate1 = new javax.swing.JLabel();
        jXDateEnd = new org.jdesktop.swingx.JXDatePicker();
        jLabelFemale31 = new javax.swing.JLabel();
        jcbApprove = new javax.swing.JComboBox();
        jcbGiver = new javax.swing.JComboBox();
        jLabelFemale32 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MAS_MSTD. PS FARM STANDARD");
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bangkok Ranch Public Co .,Ltd.");

        jPanelTransport4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCode9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode9.setForeground(java.awt.Color.red);
        jLabelCode9.setText("Standard Farm");

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabelFlockSTDate.setText("Start Date :");

        jLabelFlockSTDate1.setText("To Date :");

        jLabelFemale31.setText("Approve by  :");

        jcbApprove.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Approver" }));
        jcbApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbApproveActionPerformed(evt);
            }
        });
        jcbApprove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbApproveKeyPressed(evt);
            }
        });

        jcbGiver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Giver" }));
        jcbGiver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbGiverKeyPressed(evt);
            }
        });

        jLabelFemale32.setText("Given by  :");

        javax.swing.GroupLayout jPanelTransport4Layout = new javax.swing.GroupLayout(jPanelTransport4);
        jPanelTransport4.setLayout(jPanelTransport4Layout);
        jPanelTransport4Layout.setHorizontalGroup(
            jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                .addComponent(jLabelCode9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTransport4Layout.createSequentialGroup()
                        .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFlockSTDate1)
                            .addComponent(jLabelFlockSTDate))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jXDateStart, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jXDateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelTransport4Layout.createSequentialGroup()
                        .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFemale31)
                            .addComponent(jLabelFemale32))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                                .addComponent(btnPrint)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonClose))
                            .addComponent(jcbGiver, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTransport4Layout.setVerticalGroup(
            jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                .addComponent(jLabelCode9)
                .addGap(35, 35, 35)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFlockSTDate)
                    .addComponent(jXDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFlockSTDate1)
                    .addComponent(jXDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbGiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale32))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFemale31)
                    .addComponent(jcbApprove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(jButtonClose))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTransport4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTransport4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InsertDInvenBal() {

        LocalDate currentDate = LocalDate.parse(sdf3.format(jXDateStart.getDate()), formatter);
        LocalDate targetDate = LocalDate.parse(sdf3.format(jXDateEnd.getDate()), formatter);
        if (currentDate.isAfter(targetDate)) {
            JOptionPane.showMessageDialog(this, "เลือกวันที่เริ่มหลังจากวันจบกรุณาเลือกใหม่ครับ");

        } else {
//            while (!currentDate.isAfter(targetDate)) {
//                cid.DeleteDInvenBal(BRLogin.vFarm, currentDate.format(formatter2), BRLogin.vDuckBreed, BRLogin.vDuckBreedAll);
//                cid.InsertMTranDInvenBal(BRLogin.vFarm, currentDate.format(formatter2), sdf2.format(jXDateStart.getDate()), BRLogin.vDuckBreed, BRLogin.vDuckBreedAll);
//                currentDate = currentDate.plusDays(1);
//            }
cid.DeleteDInvenBal(BRLogin.vFarm, sdf.format(jXDateStart.getDate()), BRLogin.vDuckBreed, BRLogin.vDuckBreedAll);
        cid.InsertMTranDInvenBal(BRLogin.vFarm, sdf.format(jXDateStart.getDate()), sdf2.format(jXDateStart.getDate()), BRLogin.vDuckBreed, BRLogin.vDuckBreedAll);
        }

    }

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        if (jcbApprove.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Select Approver!");
        } else if (jcbGiver.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Select Giver!");
        } else {
            btnPrint.enable(false);
            InsertDInvenBal();
            cgr.rBR01R004("BR01R004_CM", BRLogin.vFarm, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll, sdf2.format(jXDateStart.getDate()), sdf2.format(jXDateEnd.getDate()), jcbGiver.getSelectedItem().toString(), jcbApprove.getSelectedItem().toString());
            btnPrint.enable(true);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jcbApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbApproveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbApproveActionPerformed

    private void jcbApproveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbApproveKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbApproveKeyPressed

    private void jcbGiverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbGiverKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGiverKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BR01R004_CM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BR01R004_CM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BR01R004_CM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BR01R004_CM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BR01R004_CM().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCode9;
    private javax.swing.JLabel jLabelFemale31;
    private javax.swing.JLabel jLabelFemale32;
    private javax.swing.JLabel jLabelFlockSTDate;
    private javax.swing.JLabel jLabelFlockSTDate1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelTransport4;
    private org.jdesktop.swingx.JXDatePicker jXDateEnd;
    private org.jdesktop.swingx.JXDatePicker jXDateStart;
    private javax.swing.JComboBox jcbApprove;
    private javax.swing.JComboBox jcbGiver;
    // End of variables declaration//GEN-END:variables
}
