/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BRFARM;

import java.awt.Toolkit;
import java.text.ParseException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Wattana
 */
public class BRDescEggTrans02 extends javax.swing.JFrame {

    public static String JPanel = "Transfer";
    public static String vDESC_DATE, vDESC_TRUCKNO, vDESC_HCCBW, vDESC_HCCAW, vDESC_HCD, vDESC_HCS, vDESC_HCDT, vDESC_HCTTL;
    public static String OnChange;
    public static String FrameOpen = "Yes";
    String Place = "0";
    String Weather = "0";
    String StsUpdateEggTransfer = "No";
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    DefaultTableModel model;
    ClassReturnData crd = new ClassReturnData();
    ClassInsertData cid = new ClassInsertData();
    ClassListData cld = new ClassListData();
    Calendar cal = Calendar.getInstance();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy", Locale.US);
    SimpleDateFormat stf = new SimpleDateFormat("HH:mm a");
    final Date startDate = new Date();
    SpinnerDateModel sdmST1 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    SpinnerDateModel sdmST2 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    SpinnerDateModel sdmAR1 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    SpinnerDateModel sdmAR2 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    JSpinner spnST1 = new JSpinner(sdmST1);
    JSpinner spnST2 = new JSpinner(sdmST2);
    JSpinner spnAR1 = new JSpinner(sdmAR1);
    JSpinner spnAR2 = new JSpinner(sdmAR2);
    JSpinner.DateEditor dedST1 = new JSpinner.DateEditor(spnST1, "HH:mm a");
    JSpinner.DateEditor dedST2 = new JSpinner.DateEditor(spnST2, "HH:mm a");
    JSpinner.DateEditor dedAR1 = new JSpinner.DateEditor(spnAR1, "HH:mm a");
    JSpinner.DateEditor dedAR2 = new JSpinner.DateEditor(spnAR2, "HH:mm a");
    DefaultTableModel mEggDesc;

    /**
     * Creates new form M001Farm
     */
    public BRDescEggTrans02() {
        initComponents();
        this.setTitle("BR01E008. Description Egg Transfer : " + BRLogin.vDuckBreed + " " + BRLogin.vDuckBreedDesc + " : " + BRLogin.vFarm + " " + BRLogin.vFarmDesc);
        jcbFarm.setModel(new DefaultComboBoxModel(cld.GetResultFarmDesc(BRLogin.vFarm).toArray()));
        jcbReceive.setModel(new DefaultComboBoxModel(cld.GetResultUserDriver(BRLogin.vFarm).toArray()));
        jcbGiven.setModel(new DefaultComboBoxModel(cld.GetResultUserNonAppr(BRLogin.vFarm).toArray()));
        jcbApprove.setModel(new DefaultComboBoxModel(cld.GetResultUserAppr(BRLogin.vFarm).toArray()));
        jcbEggTran.setModel(new DefaultComboBoxModel(cld.GetResultEggTran(BRLogin.vFarm, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll).toArray()));
        jTextCert.setText(crd.CheckCert(BRLogin.vFarm));
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        Date startTime = cal.getTime();
        jsTimeIn.setModel(sdmST1);
        jsTimeIn.setEditor(dedST1);
        jsTimeOut.setModel(sdmAR1);
        jsTimeOut.setEditor(dedAR1);
        jsTimeIn.setValue(startTime);
        jsTimeOut.setValue(startTime);
        jcbFarm.setSelectedIndex(1);
        mEggDesc = (DefaultTableModel) jTableTransection.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane = new javax.swing.JTabbedPane();
        jpDescription = new javax.swing.JPanel();
        jcbFarm = new javax.swing.JComboBox();
        jButtonClose = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPanelTransport = new javax.swing.JPanel();
        jLabelCode2 = new javax.swing.JLabel();
        jTextTruckNo = new javax.swing.JTextField();
        jLabelCar1 = new javax.swing.JLabel();
        jLabelST1 = new javax.swing.JLabel();
        jLabelAR1 = new javax.swing.JLabel();
        jsTimeIn = new javax.swing.JSpinner();
        jsTimeOut = new javax.swing.JSpinner();
        jcbReceive = new javax.swing.JComboBox();
        jcbApprove = new javax.swing.JComboBox();
        jcbGiven = new javax.swing.JComboBox();
        jLabelFarm = new javax.swing.JLabel();
        jPanelTransport26 = new javax.swing.JPanel();
        jLabelCode31 = new javax.swing.JLabel();
        jLabelFemale54 = new javax.swing.JLabel();
        jTextTempR = new javax.swing.JTextField();
        jLabelFemale57 = new javax.swing.JLabel();
        jTextCONC = new javax.swing.JTextField();
        jTextPHWT = new javax.swing.JTextField();
        jLabelFemale58 = new javax.swing.JLabel();
        jLabelFemale59 = new javax.swing.JLabel();
        jTextTempWT = new javax.swing.JTextField();
        jTextTimeW = new javax.swing.JTextField();
        jLabelFemale61 = new javax.swing.JLabel();
        jLabelFemale62 = new javax.swing.JLabel();
        jTextRemark2 = new javax.swing.JTextField();
        jLabelFemale63 = new javax.swing.JLabel();
        jTextRemark1 = new javax.swing.JTextField();
        jLabelFlockSTDate = new javax.swing.JLabel();
        jLabelFarm1 = new javax.swing.JLabel();
        jTextCert = new javax.swing.JTextField();
        jPanelTransport4 = new javax.swing.JPanel();
        jLabelCode9 = new javax.swing.JLabel();
        jLabelFemale29 = new javax.swing.JLabel();
        jTextHCCBW = new javax.swing.JTextField();
        jLabelFemale43 = new javax.swing.JLabel();
        jTextHCTTL = new javax.swing.JTextField();
        jTextHCDT = new javax.swing.JTextField();
        jLabelFemale44 = new javax.swing.JLabel();
        jLabelFemale45 = new javax.swing.JLabel();
        jTextHCS = new javax.swing.JTextField();
        jTextHCD = new javax.swing.JTextField();
        jLabelFemale46 = new javax.swing.JLabel();
        jLabelFemale47 = new javax.swing.JLabel();
        jTextHCCAW = new javax.swing.JTextField();
        jLabelStart1 = new javax.swing.JLabel();
        jbFarm = new javax.swing.JCheckBox();
        jbHatchery = new javax.swing.JCheckBox();
        jPanelTransport27 = new javax.swing.JPanel();
        jLabelCode32 = new javax.swing.JLabel();
        jLabelFemale60 = new javax.swing.JLabel();
        jTextTempCS = new javax.swing.JTextField();
        jTextTruckBHC = new javax.swing.JTextField();
        jLabelFemale64 = new javax.swing.JLabel();
        jLabelFemale65 = new javax.swing.JLabel();
        jTextTruckB = new javax.swing.JTextField();
        jLabelStart = new javax.swing.JLabel();
        jbNormal = new javax.swing.JCheckBox();
        jbRain = new javax.swing.JCheckBox();
        jLabelFemale30 = new javax.swing.JLabel();
        jLabelFemale31 = new javax.swing.JLabel();
        jLabelFemale32 = new javax.swing.JLabel();
        jcbEggTran = new javax.swing.JComboBox();
        jpTransaction = new javax.swing.JPanel();
        jPanelTransection = new javax.swing.JScrollPane();
        jTableTransection = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSave = new javax.swing.JMenu();
        jMenuCreate = new javax.swing.JMenu();
        jMenuChange = new javax.swing.JMenu();
        jMenuDelete = new javax.swing.JMenu();
        jMenuRefresh = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PS01E001. PS GROWER SETTING");
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jpDescription.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpDescriptionComponentShown(evt);
            }
        });

        jcbFarm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Farm" }));
        jcbFarm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbFarmKeyPressed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonSave.setText("Submit");
        jButtonSave.setToolTipText("");
        jButtonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseClicked(evt);
            }
        });
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jPanelTransport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCode2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode2.setForeground(java.awt.Color.red);
        jLabelCode2.setText("Transport");

        jTextTruckNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTruckNoActionPerformed(evt);
            }
        });

        jLabelCar1.setText("ทะเบียนรถ #1 :");

        jLabelST1.setText("เวลาเริ่ม :");

        jLabelAR1.setText("เวลาถึงฟาร์ม :");

        javax.swing.GroupLayout jPanelTransportLayout = new javax.swing.GroupLayout(jPanelTransport);
        jPanelTransport.setLayout(jPanelTransportLayout);
        jPanelTransportLayout.setHorizontalGroup(
            jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextTruckNo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabelST1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsTimeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAR1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTransportLayout.createSequentialGroup()
                .addComponent(jLabelCode2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelTransportLayout.setVerticalGroup(
            jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransportLayout.createSequentialGroup()
                .addComponent(jLabelCode2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCar1)
                        .addComponent(jTextTruckNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAR1)
                        .addComponent(jsTimeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelST1)
                        .addComponent(jsTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcbReceive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Farm" }));
        jcbReceive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbReceiveKeyPressed(evt);
            }
        });

        jcbApprove.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Farm" }));
        jcbApprove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbApproveKeyPressed(evt);
            }
        });

        jcbGiven.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Farm" }));
        jcbGiven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbGivenKeyPressed(evt);
            }
        });

        jLabelFarm.setText("Farm Code :");

        jPanelTransport26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCode31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode31.setForeground(java.awt.Color.red);
        jLabelCode31.setText("Detail 2");

        jLabelFemale54.setText("อุณหภูมิขณะล้าง :");

        jTextTempR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTempRFocusLost(evt);
            }
        });

        jLabelFemale57.setText("ความเข้มข้น :");

        jTextCONC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextCONCFocusLost(evt);
            }
        });

        jTextPHWT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPHWTFocusLost(evt);
            }
        });

        jLabelFemale58.setText("PH น้ำ :");

        jLabelFemale59.setText("อุณหภูมิน้ำ :");

        jTextTempWT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTempWTFocusLost(evt);
            }
        });

        jTextTimeW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTimeWFocusLost(evt);
            }
        });

        jLabelFemale61.setText("ระยะเวลาล้าง :");

        jLabelFemale62.setText("ไข่สกปรก :");

        jTextRemark2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextRemark2FocusLost(evt);
            }
        });

        jLabelFemale63.setText("หมายเหตุ :");

        jTextRemark1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextRemark1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelTransport26Layout = new javax.swing.GroupLayout(jPanelTransport26);
        jPanelTransport26.setLayout(jPanelTransport26Layout);
        jPanelTransport26Layout.setHorizontalGroup(
            jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport26Layout.createSequentialGroup()
                .addComponent(jLabelCode31)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelTransport26Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTransport26Layout.createSequentialGroup()
                        .addComponent(jLabelFemale63)
                        .addGap(18, 18, 18)
                        .addComponent(jTextRemark1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTransport26Layout.createSequentialGroup()
                        .addComponent(jLabelFemale62)
                        .addGap(18, 18, 18)
                        .addComponent(jTextRemark2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTransport26Layout.createSequentialGroup()
                        .addComponent(jLabelFemale61)
                        .addGap(18, 18, 18)
                        .addComponent(jTextTimeW, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTransport26Layout.createSequentialGroup()
                        .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFemale58)
                            .addComponent(jLabelFemale57)
                            .addComponent(jLabelFemale59)
                            .addComponent(jLabelFemale54))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCONC, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTempWT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPHWT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTempR, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelTransport26Layout.setVerticalGroup(
            jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport26Layout.createSequentialGroup()
                .addComponent(jLabelCode31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTempR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale54))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTempWT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale59))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPHWT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale58))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCONC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale57))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTimeW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale61))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextRemark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale62))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextRemark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale63))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelFlockSTDate.setText("Transfer Date :");

        jLabelFarm1.setText("Certification No :");

        jTextCert.setEditable(false);
        jTextCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCertActionPerformed(evt);
            }
        });

        jPanelTransport4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCode9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode9.setForeground(java.awt.Color.red);
        jLabelCode9.setText("Detail  1");

        jLabelFemale29.setText("ไข่แตกก่อนล้าง :");

        jTextHCCBW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextHCCBWFocusLost(evt);
            }
        });

        jLabelFemale43.setText("จำนวนไข่ทั้งหมด :");

        jTextHCTTL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextHCTTLFocusLost(evt);
            }
        });

        jTextHCDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextHCDTFocusLost(evt);
            }
        });

        jLabelFemale44.setText("ไข่ทำลาย :");

        jLabelFemale45.setText("ไข่เล็ก :");

        jTextHCS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextHCSFocusLost(evt);
            }
        });

        jTextHCD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextHCDFocusLost(evt);
            }
        });

        jLabelFemale46.setText("ไข่แฝด :");

        jLabelFemale47.setText("ไข่แตกหลังล้าง :");

        jTextHCCAW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextHCCAWFocusLost(evt);
            }
        });

        jLabelStart1.setText("สถานที่ทำลาย :");

        jbFarm.setText("1.ฟาร์ม");
        jbFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFarmActionPerformed(evt);
            }
        });

        jbHatchery.setText("2.โรงฟัก");
        jbHatchery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHatcheryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTransport4Layout = new javax.swing.GroupLayout(jPanelTransport4);
        jPanelTransport4.setLayout(jPanelTransport4Layout);
        jPanelTransport4Layout.setHorizontalGroup(
            jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                .addComponent(jLabelCode9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelTransport4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                                .addComponent(jLabelStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbFarm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbHatchery))
                            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFemale46)
                                    .addComponent(jLabelFemale45)
                                    .addComponent(jLabelFemale47)
                                    .addComponent(jLabelFemale29)
                                    .addComponent(jLabelFemale44))
                                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTransport4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextHCS, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextHCCAW, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextHCD, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextHCCBW, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelTransport4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextHCDT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanelTransport4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabelFemale43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextHCTTL, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelTransport4Layout.setVerticalGroup(
            jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport4Layout.createSequentialGroup()
                .addComponent(jLabelCode9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHCCBW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale29))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHCCAW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale47))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale46))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale45))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale44))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHCTTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale43))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStart1)
                    .addComponent(jbFarm)
                    .addComponent(jbHatchery))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTransport27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCode32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode32.setForeground(java.awt.Color.red);
        jLabelCode32.setText("Detail 3");

        jLabelFemale60.setText("อุณหภูมิห้องเย็น ก่อนส่งไข่ :");

        jTextTempCS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTempCSFocusLost(evt);
            }
        });

        jTextTruckBHC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTruckBHCFocusLost(evt);
            }
        });

        jLabelFemale64.setText("อุณหภูมิรถบรรทุก ก่อนไปโรงฟัก :");

        jLabelFemale65.setText("อุณหภูมิรถบรรทุก ก่อนขึ้นไข่ :");

        jTextTruckB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTruckBFocusLost(evt);
            }
        });

        jLabelStart.setText("สภาพภูมิอากาศ :");

        jbNormal.setText("1.ปกติ");
        jbNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNormalActionPerformed(evt);
            }
        });

        jbRain.setText("2.ฝนตก");
        jbRain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTransport27Layout = new javax.swing.GroupLayout(jPanelTransport27);
        jPanelTransport27.setLayout(jPanelTransport27Layout);
        jPanelTransport27Layout.setHorizontalGroup(
            jPanelTransport27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport27Layout.createSequentialGroup()
                .addComponent(jLabelCode32)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelTransport27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTransport27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelStart)
                    .addComponent(jLabelFemale64)
                    .addComponent(jLabelFemale65)
                    .addComponent(jLabelFemale60))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextTruckB, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTruckBHC, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTempCS, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTransport27Layout.createSequentialGroup()
                        .addComponent(jbNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbRain)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTransport27Layout.setVerticalGroup(
            jPanelTransport27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransport27Layout.createSequentialGroup()
                .addComponent(jLabelCode32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTransport27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTempCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale60))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTruckB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale65))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTruckBHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale64))
                .addGap(18, 18, 18)
                .addGroup(jPanelTransport27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStart)
                    .addComponent(jbNormal)
                    .addComponent(jbRain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelFemale30.setText("Receive by  :");

        jLabelFemale31.setText("Approve by  :");

        jLabelFemale32.setText("Given by  :");

        jcbEggTran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Date" }));

        javax.swing.GroupLayout jpDescriptionLayout = new javax.swing.GroupLayout(jpDescription);
        jpDescription.setLayout(jpDescriptionLayout);
        jpDescriptionLayout.setHorizontalGroup(
            jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(jLabelFarm)
                        .addGap(10, 10, 10)
                        .addComponent(jcbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFarm1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextCert, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFlockSTDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbEggTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(jLabelFemale30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelFemale31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFemale32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose))
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(jPanelTransport4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelTransport26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelTransport27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelTransport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDescriptionLayout.setVerticalGroup(
            jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFlockSTDate)
                        .addComponent(jTextCert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbEggTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFarm)
                        .addComponent(jcbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFarm1)))
                .addGap(11, 11, 11)
                .addComponent(jPanelTransport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTransport27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTransport4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTransport26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFemale30)
                    .addComponent(jcbReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale31)
                    .addComponent(jcbApprove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale32)
                    .addComponent(jcbGiven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonSave))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Transfer Description", jpDescription);

        jpTransaction.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpTransactionComponentShown(evt);
            }
        });

        jTableTransection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "วันที่ส่งไข่", "รอบส่ง", "ทะเบียนรถ", "ไข่แตกก่อนล้าง", "ไข่แตกหลังล้าง", "ไข่แฝด", "ไข่เล็ก", "ไข่ทำลาย", "จำนวนไข่ทั้งหมด"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTransection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTransectionMouseClicked(evt);
            }
        });
        jPanelTransection.setViewportView(jTableTransection);

        javax.swing.GroupLayout jpTransactionLayout = new javax.swing.GroupLayout(jpTransaction);
        jpTransaction.setLayout(jpTransactionLayout);
        jpTransactionLayout.setHorizontalGroup(
            jpTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTransection, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
        );
        jpTransactionLayout.setVerticalGroup(
            jpTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTransection, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("History Transfer", jpTransaction);

        jMenuSave.setText("Save :");
        jMenuBar1.add(jMenuSave);

        jMenuCreate.setText("Create :");
        jMenuCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCreateMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCreate);

        jMenuChange.setText("Change :");
        jMenuChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuChangeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuChange);

        jMenuDelete.setText("Delete :");
        jMenuDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDeleteMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuDelete);

        jMenuRefresh.setText("Refresh :");
        jMenuRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRefreshMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuRefresh);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ResetModel() {

        while (mEggDesc.getRowCount() > 0) {
            for (int i = 0; i < mEggDesc.getRowCount(); ++i) {
                mEggDesc.removeRow(i);
            }
        }

    }

    private void ResetText() {
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        Date startTime = cal.getTime();
        jTextTruckNo.setText("");
        jsTimeIn.setValue(startTime);
        jsTimeOut.setValue(startTime);
        jTextHCCBW.setText("");
        jTextHCCAW.setText("");
        jTextHCD.setText("");
        jTextHCS.setText("");
        jTextHCDT.setText("");
        jTextHCTTL.setText("");
        jbFarm.setSelected(false);
        jbHatchery.setSelected(false);
        jTextTempR.setText("");
        jTextTempWT.setText("");
        jTextPHWT.setText("");
        jTextCONC.setText("");
        jTextTimeW.setText("");
        jTextRemark2.setText("");
        jTextRemark1.setText("");
        jTextTempCS.setText("");
        jTextTruckB.setText("");
        jTextTruckBHC.setText("");
        jbNormal.setSelected(false);
        jbRain.setSelected(false);
        jcbReceive.setSelectedIndex(0);
        jcbApprove.setSelectedIndex(0);
        jcbGiven.setSelectedIndex(0);
    }

    private void UpdateEggTransfer() {

        String[] getEggTran = jcbEggTran.getSelectedItem().toString().split(":");
        Date getDate = null;
        String getLotDate = "";

        try {
            getDate = new SimpleDateFormat("dd/MM/yyyy", Locale.US).parse(getEggTran[0]);
        } catch (ParseException ex) {
            Logger.getLogger(BRTrans01.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (getEggTran.length >= 2) {
            getLotDate = getEggTran[1].trim();
        }

        String vCountMDesc = crd.CheckMDescDuplicate(BRLogin.vFarm, sdf.format(getDate), getLotDate, BRLogin.vDuckBreed);

        if (Integer.valueOf(vCountMDesc) > 0) {
            JOptionPane.showMessageDialog(null, "Egg Description Already");
        } else {
            cid.InsertEggDescription(BRLogin.vFarm, sdf.format(getDate), jTextHCCBW.getText(),  jTextHCCAW.getText(), jTextHCD.getText(), jTextHCS.getText(), jTextHCDT.getText(),
                     jTextHCTTL.getText(), Place, jTextTempR.getText(),  jTextTempWT.getText(), jTextTimeW.getText(), getLotDate,  jTextPHWT.getText(),  jTextCONC.getText(),
                    jTextTempCS.getText(), jTextTruckB.getText(), jTextTruckBHC.getText(), Weather, jcbGiven.getSelectedItem().toString(), jcbReceive.getSelectedItem().toString(), jcbApprove.getSelectedItem().toString(),
                    stf.format(jsTimeIn.getValue()), jTextTruckNo.getText(), stf.format(jsTimeOut.getValue()), jTextRemark1.getText(), jTextRemark2.getText(), jTextCert.getText(), BRLogin.vDuckBreed);
            StsUpdateEggTransfer = "Yes";
        }

    }

    private void EggDescription() {

        List<String> getListEggDesc = cld.GetResultEggDesc(BRLogin.vFarm, BRLogin.vDuckBreed);

        ResetModel();
        for (int i = 0; i < getListEggDesc.size(); i++) {
            String[] CheckEggTransection = getListEggDesc.get(i).split(";");
            mEggDesc.insertRow(mEggDesc.getRowCount(), new Object[]{
                CheckEggTransection[0].trim(),
                CheckEggTransection[1].trim(),
                CheckEggTransection[2].trim(),
                CheckEggTransection[3].trim(),
                CheckEggTransection[4].trim(),
                CheckEggTransection[5].trim(),
                CheckEggTransection[6].trim(),
                CheckEggTransection[7].trim(),
                CheckEggTransection[8].trim()
            });
        }

    }

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here: 

        try {

            if ("Please Select : Farm".equals(jcbFarm.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(null, "Please Select Farm");
                jcbFarm.requestFocusInWindow();
            } else if ("".equals(jTextTruckNo.getText())) {
                JOptionPane.showMessageDialog(null, "Please Insert Truck No");
                jTextTruckNo.requestFocusInWindow();
            } else if ("".equals(jTextHCTTL.getText())) {
                JOptionPane.showMessageDialog(null, "Please Insert Egg");
                jTextHCTTL.requestFocusInWindow();
            } else if (jbFarm.isSelected() == false && jbHatchery.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Please Select Place");
                jbFarm.requestFocusInWindow();
            } else if (jbNormal.isSelected() == false && jbRain.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Please Select Weather");
                jbNormal.requestFocusInWindow();
            } else if ("Please Select : Receive".equals(jcbReceive.getSelectedItem())) {
                JOptionPane.showMessageDialog(null, "Please Insert Receive");
                jcbReceive.requestFocusInWindow();
            } else if ("Please Select : Approve".equals(jcbApprove.getSelectedItem())) {
                JOptionPane.showMessageDialog(null, "Please Insert Approve");
                jcbApprove.requestFocusInWindow();
            } else if ("Please Select : Given".equals(jcbGiven.getSelectedItem())) {
                JOptionPane.showMessageDialog(null, "Please Insert Given");
                jcbGiven.requestFocusInWindow();
            } else {
                UpdateEggTransfer();
                if ("Yes".equals(StsUpdateEggTransfer)) {
                    JOptionPane.showMessageDialog(null, "Data Post Completed");
                    StsUpdateEggTransfer = "No";
                    ResetText();
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:  
        if (!"Yes".equals(FrameOpen)) {

            if ("History".equals(JPanel)) {
                EggDescription();
            }

            FrameOpen = "Yes";
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jcbFarmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbFarmKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFarmKeyPressed

    private void jTextTruckNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTruckNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTruckNoActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jTextHCCBWFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextHCCBWFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHCCBWFocusLost

    private void jbNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNormalActionPerformed
        // TODO add your handling code here:
        if (jbNormal.isSelected() == true) {
            Weather = "1";
            jbRain.setSelected(false);
        } else {
            Weather = null;
        }
    }//GEN-LAST:event_jbNormalActionPerformed

    private void jbRainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRainActionPerformed
        // TODO add your handling code here:
        if (jbRain.isSelected() == true) {
            Weather = "2";
            jbNormal.setSelected(false);
        } else {
            Weather = null;
        }
    }//GEN-LAST:event_jbRainActionPerformed

    private void jTextCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCertActionPerformed

    private void jTextHCTTLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextHCTTLFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHCTTLFocusLost

    private void jTextHCDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextHCDTFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHCDTFocusLost

    private void jTextHCSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextHCSFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHCSFocusLost

    private void jTextHCDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextHCDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHCDFocusLost

    private void jTextHCCAWFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextHCCAWFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHCCAWFocusLost

    private void jbFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFarmActionPerformed
        // TODO add your handling code here:
        if (jbFarm.isSelected() == true) {
            Place = "1";
            jbHatchery.setSelected(false);
        } else {
            Place = null;
        }
    }//GEN-LAST:event_jbFarmActionPerformed

    private void jbHatcheryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHatcheryActionPerformed
        // TODO add your handling code here:
        if (jbHatchery.isSelected() == true) {
            Place = "2";
            jbFarm.setSelected(false);
        } else {
            Place = null;
        }
    }//GEN-LAST:event_jbHatcheryActionPerformed

    private void jTextTempRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTempRFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTempRFocusLost

    private void jTextCONCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCONCFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCONCFocusLost

    private void jTextPHWTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPHWTFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPHWTFocusLost

    private void jTextTempWTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTempWTFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTempWTFocusLost

    private void jTextTruckBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTruckBFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTruckBFocusLost

    private void jTextTruckBHCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTruckBHCFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTruckBHCFocusLost

    private void jTextTempCSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTempCSFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTempCSFocusLost

    private void jTextTimeWFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTimeWFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTimeWFocusLost

    private void jTextRemark2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextRemark2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRemark2FocusLost

    private void jTextRemark1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextRemark1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRemark1FocusLost

    private void jcbReceiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbReceiveKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbReceiveKeyPressed

    private void jcbApproveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbApproveKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbApproveKeyPressed

    private void jcbGivenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbGivenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGivenKeyPressed

    private void jpDescriptionComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpDescriptionComponentShown
        // TODO add your handling code here:
        JPanel = "Transfer";
        jMenuSave.setEnabled(false);
        jMenuCreate.setEnabled(false);
        jMenuChange.setEnabled(false);
        jMenuDelete.setEnabled(false);
        jMenuRefresh.setEnabled(false);
    }//GEN-LAST:event_jpDescriptionComponentShown

    private void jpTransactionComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpTransactionComponentShown
        // TODO add your handling code here:
        JPanel = "History";
        EggDescription();
        jMenuSave.setEnabled(false);
        jMenuCreate.setEnabled(false);
        jMenuChange.setEnabled(true);
        jMenuDelete.setEnabled(true);
        jMenuRefresh.setEnabled(true);
    }//GEN-LAST:event_jpTransactionComponentShown

    private void jTableTransectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTransectionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableTransectionMouseClicked

    private void jMenuCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCreateMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuCreateMouseClicked

    private void jMenuChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuChangeMouseClicked
        // TODO add your handling code here
        int index = jTableTransection.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(null, "Please select " + JPanel + " record for Change!");
        } else {
            vDESC_DATE = String.valueOf(mEggDesc.getValueAt(jTableTransection.getSelectedRow(), 0));
            vDESC_TRUCKNO = String.valueOf(mEggDesc.getValueAt(jTableTransection.getSelectedRow(), 1));
            vDESC_HCCBW = String.valueOf(mEggDesc.getValueAt(jTableTransection.getSelectedRow(), 2));
            vDESC_HCCAW = String.valueOf(mEggDesc.getValueAt(jTableTransection.getSelectedRow(), 3));
            vDESC_HCD = String.valueOf(mEggDesc.getValueAt(jTableTransection.getSelectedRow(), 4));
            vDESC_HCS = String.valueOf(mEggDesc.getValueAt(jTableTransection.getSelectedRow(), 5));
            vDESC_HCDT = String.valueOf(mEggDesc.getValueAt(jTableTransection.getSelectedRow(), 6));
            vDESC_HCTTL = String.valueOf(mEggDesc.getValueAt(jTableTransection.getSelectedRow(), 7));
            new BRDescEggTrans03().setVisible(true);
            this.OnChange = "Yes";
        }
    }//GEN-LAST:event_jMenuChangeMouseClicked

    private void jMenuDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDeleteMouseClicked
        // TODO add your handling code here:
        if ("History".equals(JPanel) && jMenuDelete.isEnabled() == true) {

            int index = jTableTransection.getSelectedRow();
            if (index < 0) {
                JOptionPane.showMessageDialog(null, "Please select " + JPanel + " record for Delete!");
            } else {

                String DESC_DATE = jTableTransection.getValueAt(index, 0).toString();
                String DESC_TRUCKNO = jTableTransection.getValueAt(index, 1).toString();

                Object[] options = {"Yes", "No"};
                int n = JOptionPane.showOptionDialog(null, "Do you want to Delete data?",
                        "Confirm to Delete?",
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, options,
                        options[1]);
                if (n == 0) // Confirm Delete = Yes
                {
                    cid.DeleteEggDesc(BRLogin.vFarm, DESC_DATE, DESC_TRUCKNO, BRLogin.vDuckBreed); // Delete Data
                    JOptionPane.showMessageDialog(null, "Delete Success");
                    EggDescription(); //Reload Table
                }
            }
        }
    }//GEN-LAST:event_jMenuDeleteMouseClicked

    private void jMenuRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRefreshMouseClicked
        // TODO add your handling code here:
        if ("History".equals(JPanel)) {
            EggDescription();
        }
    }//GEN-LAST:event_jMenuRefreshMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BRDescEggTrans02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BRDescEggTrans02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BRDescEggTrans02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BRDescEggTrans02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BRDescEggTrans02().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelAR1;
    private javax.swing.JLabel jLabelCar1;
    private javax.swing.JLabel jLabelCode2;
    private javax.swing.JLabel jLabelCode31;
    private javax.swing.JLabel jLabelCode32;
    private javax.swing.JLabel jLabelCode9;
    private javax.swing.JLabel jLabelFarm;
    private javax.swing.JLabel jLabelFarm1;
    private javax.swing.JLabel jLabelFemale29;
    private javax.swing.JLabel jLabelFemale30;
    private javax.swing.JLabel jLabelFemale31;
    private javax.swing.JLabel jLabelFemale32;
    private javax.swing.JLabel jLabelFemale43;
    private javax.swing.JLabel jLabelFemale44;
    private javax.swing.JLabel jLabelFemale45;
    private javax.swing.JLabel jLabelFemale46;
    private javax.swing.JLabel jLabelFemale47;
    private javax.swing.JLabel jLabelFemale54;
    private javax.swing.JLabel jLabelFemale57;
    private javax.swing.JLabel jLabelFemale58;
    private javax.swing.JLabel jLabelFemale59;
    private javax.swing.JLabel jLabelFemale60;
    private javax.swing.JLabel jLabelFemale61;
    private javax.swing.JLabel jLabelFemale62;
    private javax.swing.JLabel jLabelFemale63;
    private javax.swing.JLabel jLabelFemale64;
    private javax.swing.JLabel jLabelFemale65;
    private javax.swing.JLabel jLabelFlockSTDate;
    private javax.swing.JLabel jLabelST1;
    private javax.swing.JLabel jLabelStart;
    private javax.swing.JLabel jLabelStart1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuChange;
    private javax.swing.JMenu jMenuCreate;
    private javax.swing.JMenu jMenuDelete;
    private javax.swing.JMenu jMenuRefresh;
    private javax.swing.JMenu jMenuSave;
    private javax.swing.JScrollPane jPanelTransection;
    private javax.swing.JPanel jPanelTransport;
    private javax.swing.JPanel jPanelTransport26;
    private javax.swing.JPanel jPanelTransport27;
    private javax.swing.JPanel jPanelTransport4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTableTransection;
    private javax.swing.JTextField jTextCONC;
    private javax.swing.JTextField jTextCert;
    private javax.swing.JTextField jTextHCCAW;
    private javax.swing.JTextField jTextHCCBW;
    private javax.swing.JTextField jTextHCD;
    private javax.swing.JTextField jTextHCDT;
    private javax.swing.JTextField jTextHCS;
    private javax.swing.JTextField jTextHCTTL;
    private javax.swing.JTextField jTextPHWT;
    private javax.swing.JTextField jTextRemark1;
    private javax.swing.JTextField jTextRemark2;
    private javax.swing.JTextField jTextTempCS;
    private javax.swing.JTextField jTextTempR;
    private javax.swing.JTextField jTextTempWT;
    private javax.swing.JTextField jTextTimeW;
    private javax.swing.JTextField jTextTruckB;
    private javax.swing.JTextField jTextTruckBHC;
    private javax.swing.JTextField jTextTruckNo;
    private javax.swing.JCheckBox jbFarm;
    private javax.swing.JCheckBox jbHatchery;
    private javax.swing.JCheckBox jbNormal;
    private javax.swing.JCheckBox jbRain;
    private javax.swing.JComboBox jcbApprove;
    private javax.swing.JComboBox jcbEggTran;
    private javax.swing.JComboBox jcbFarm;
    private javax.swing.JComboBox jcbGiven;
    private javax.swing.JComboBox jcbReceive;
    private javax.swing.JPanel jpDescription;
    private javax.swing.JPanel jpTransaction;
    private javax.swing.JSpinner jsTimeIn;
    private javax.swing.JSpinner jsTimeOut;
    // End of variables declaration//GEN-END:variables

}
