/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BRFARM;

import static BRFARM.BRData01.vDUCK_DATEREC;
import static BRFARM.BRData01.vDUCK_FARM;
import static BRFARM.BRData01.vDUCK_FLOCK;
import static BRFARM.BRData01.vDUCK_HOUSE;
import static BRFARM.BRData01.vDUCK_MO;
import static BRFARM.BRData01.vDUCK_Type;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.ParseException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Wattana
 */
public class BRDuck03 extends javax.swing.JFrame {

    int FLFTotal, FLFDeadAP, FLFCullAP, FLFDeadT, FLFCullT, FLFDeadVac, FLFSumTotal;
    int FLMTotal, FLMDeadAP, FLMCullAP, FLMDeadT, FLMCullT, FLMDeadVac, FLMSumTotal;
    int MLFTotal, MLFDeadAP, MLFCullAP, MLFDeadT, MLFCullT, MLFDeadVac, MLFSumTotal;
    int MLMTotal, MLMDeadAP, MLMCullAP, MLMDeadT, MLMCullT, MLMDeadVac, MLMSumTotal;
    String Flock, House, DateRec, MO, Table, Farm;
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    DefaultTableModel model;
    ClassReturnData crd = new ClassReturnData();
    ClassInsertData cid = new ClassInsertData();
    ClassListData cld = new ClassListData();
    Calendar cal = Calendar.getInstance();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy", Locale.US);
    SimpleDateFormat stf = new SimpleDateFormat("HH:mm a");
    final Date startDate = new Date();
    SpinnerDateModel sdmST1 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    SpinnerDateModel sdmST2 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    SpinnerDateModel sdmAR1 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    SpinnerDateModel sdmAR2 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    JSpinner spnST1 = new JSpinner(sdmST1);
    JSpinner spnST2 = new JSpinner(sdmST2);
    JSpinner spnAR1 = new JSpinner(sdmAR1);
    JSpinner spnAR2 = new JSpinner(sdmAR2);
    JSpinner.DateEditor dedST1 = new JSpinner.DateEditor(spnST1, "HH:mm a");
    JSpinner.DateEditor dedST2 = new JSpinner.DateEditor(spnST2, "HH:mm a");
    JSpinner.DateEditor dedAR1 = new JSpinner.DateEditor(spnAR1, "HH:mm a");
    JSpinner.DateEditor dedAR2 = new JSpinner.DateEditor(spnAR2, "HH:mm a");

    /**
     * Creates new form M001Farm
     */
    public BRDuck03() {

        initComponents();
        Date startTime = cal.getTime();
//        jsST1.setModel(sdmST1);
//        jsST1.setEditor(dedST1);
//        jsST2.setModel(sdmST2);
//        jsST2.setEditor(dedST2);
//        jsAR1.setModel(sdmAR1);
//        jsAR1.setEditor(dedAR1);
//        jsAR2.setModel(sdmAR2);
//        jsAR2.setEditor(dedAR2);
//        jsST1.setValue(startTime);
//        jsST2.setValue(startTime);
//        jsAR1.setValue(startTime);
//        jsAR2.setValue(startTime);
        jcbHouse.setModel(new DefaultComboBoxModel(cld.GetResultHouseDesc(BRLogin.vFarm, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll).toArray()));
        jcbFarm.setModel(new DefaultComboBoxModel(cld.GetResultFarmDesc(BRLogin.vFarm).toArray()));
        jcbFlock.setModel(new DefaultComboBoxModel(cld.GetResultFlockDesc(BRLogin.vFarm, BRLogin.vDuckBreed).toArray()));
        jcbHouseFLF.setModel(new DefaultComboBoxModel(cld.GetResultHouseDesc(BRLogin.vFarm, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll).toArray()));
//        jcbHouseFLM.setModel(new DefaultComboBoxModel(cld.GetResultHouseDesc(BRLogin.vFarm, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll).toArray()));
        jcbFarm.setSelectedIndex(1);
        GetData();
//        String dateString = "2024-07-10";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLabelStart = new javax.swing.JLabel();
        jcbFlock = new javax.swing.JComboBox();
        jButtonClose = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jcbHatchery = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelFML = new javax.swing.JPanel();
        jpFemale = new javax.swing.JPanel();
        jTextFLFDeadAP = new javax.swing.JTextField();
        jTextFLFCullAP = new javax.swing.JTextField();
        jTextFLFDeadT = new javax.swing.JTextField();
        jTextFLFCullT = new javax.swing.JTextField();
        jLabelFemale1 = new javax.swing.JLabel();
        jLabelFemale2 = new javax.swing.JLabel();
        jLabelFemale3 = new javax.swing.JLabel();
        jLabelFemale4 = new javax.swing.JLabel();
        jLabelFemale5 = new javax.swing.JLabel();
        jLabelFemale6 = new javax.swing.JLabel();
        jLabelFemale7 = new javax.swing.JLabel();
        jTextFLFInsert = new javax.swing.JTextField();
        jTextFLFDeadVac = new javax.swing.JTextField();
        jTextFLFTotal = new javax.swing.JTextField();
        jLabelCode1 = new javax.swing.JLabel();
        jLabelMO = new javax.swing.JLabel();
        jTextMOFLF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelHouse1 = new javax.swing.JLabel();
        jcbHouseFLF = new javax.swing.JComboBox();
        jpFemale1 = new javax.swing.JPanel();
        jTextFLMDeadAP = new javax.swing.JTextField();
        jTextFLMCullAP = new javax.swing.JTextField();
        jTextFLMDeadT = new javax.swing.JTextField();
        jTextFLMCullT = new javax.swing.JTextField();
        jLabelFemale8 = new javax.swing.JLabel();
        jLabelFemale9 = new javax.swing.JLabel();
        jLabelFemale10 = new javax.swing.JLabel();
        jLabelFemale11 = new javax.swing.JLabel();
        jLabelFemale12 = new javax.swing.JLabel();
        jLabelFemale13 = new javax.swing.JLabel();
        jLabelFemale14 = new javax.swing.JLabel();
        jTextFLMInsert = new javax.swing.JTextField();
        jTextFLMDeadVac = new javax.swing.JTextField();
        jTextFLMTotal = new javax.swing.JTextField();
        jLabelCode3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbFlight = new javax.swing.JCheckBox();
        jPanelTransport = new javax.swing.JPanel();
        jLabelCode2 = new javax.swing.JLabel();
        jTextCar1 = new javax.swing.JTextField();
        jLabelCar1 = new javax.swing.JLabel();
        jTextCar2 = new javax.swing.JTextField();
        jLabelCar2 = new javax.swing.JLabel();
        jLabelST1 = new javax.swing.JLabel();
        jLabelST2 = new javax.swing.JLabel();
        jLabelAR2 = new javax.swing.JLabel();
        jLabelTem1 = new javax.swing.JLabel();
        jTextTem1 = new javax.swing.JTextField();
        jLabelTem2 = new javax.swing.JLabel();
        jTextTem2 = new javax.swing.JTextField();
        jLabelAR1 = new javax.swing.JLabel();
        jsST1 = new javax.swing.JSpinner();
        jsAR1 = new javax.swing.JSpinner();
        jsST2 = new javax.swing.JSpinner();
        jsAR2 = new javax.swing.JSpinner();
        jLabelFlock = new javax.swing.JLabel();
        jLabelFarm = new javax.swing.JLabel();
        jLabelFlockSTDate = new javax.swing.JLabel();
        jLabelHouse = new javax.swing.JLabel();
        jXDateReceivied = new org.jdesktop.swingx.JXDatePicker();
        jcbFarm = new javax.swing.JComboBox();
        jTextFlight = new javax.swing.JTextField();
        jcbHouse = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DUCK DETAIL CHANGE PS LAYING");
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelStart.setText("ต้นทาง :");

        jcbFlock.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Flock" }));
        jcbFlock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbFlockKeyPressed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonSave.setText("Change");
        jButtonSave.setToolTipText("");
        jButtonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseClicked(evt);
            }
        });
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jcbHatchery.setText("1.โรงฟัก");
        jcbHatchery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHatcheryActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jPanelFML.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFML.setToolTipText("");
        jPanelFML.setName(""); // NOI18N
        jPanelFML.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelFMLComponentShown(evt);
            }
        });

        jpFemale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpFemale.setToolTipText("");

        jTextFLFDeadAP.setText("0");
        jTextFLFDeadAP.setEnabled(false);
        jTextFLFDeadAP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFDeadAPFocusLost(evt);
            }
        });

        jTextFLFCullAP.setText("0");
        jTextFLFCullAP.setEnabled(false);
        jTextFLFCullAP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFCullAPFocusLost(evt);
            }
        });

        jTextFLFDeadT.setText("0");
        jTextFLFDeadT.setEnabled(false);
        jTextFLFDeadT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFDeadTFocusLost(evt);
            }
        });

        jTextFLFCullT.setText("0");
        jTextFLFCullT.setEnabled(false);
        jTextFLFCullT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFCullTFocusLost(evt);
            }
        });

        jLabelFemale1.setText("ทั้งหมด :");

        jLabelFemale2.setText("ตายจากต้นทาง :");

        jLabelFemale3.setText("พิการจากต้นทาง :");

        jLabelFemale4.setText("ตายระหว่างขนส่ง :");

        jLabelFemale5.setText("พิการระหว่างขนส่ง :");

        jLabelFemale6.setText("ตายระหว่างวัคซีน :");

        jLabelFemale7.setText("ส่งเข้าฟาร์ม :");

        jTextFLFInsert.setText("0");
        jTextFLFInsert.setEnabled(false);
        jTextFLFInsert.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFInsertFocusLost(evt);
            }
        });

        jTextFLFDeadVac.setText("0");
        jTextFLFDeadVac.setEnabled(false);
        jTextFLFDeadVac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFDeadVacFocusLost(evt);
            }
        });

        jTextFLFTotal.setText("0");
        jTextFLFTotal.setEnabled(false);
        jTextFLFTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFTotalFocusLost(evt);
            }
        });

        jLabelCode1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode1.setForeground(java.awt.Color.red);
        jLabelCode1.setText("Female");

        jLabelMO.setText("MO No. :");

        jTextMOFLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMOFLFActionPerformed(evt);
            }
        });

        jLabel1.setText("________________________________________________");

        jLabelHouse1.setText("House Code :");

        jcbHouseFLF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select House" }));
        jcbHouseFLF.setEnabled(false);
        jcbHouseFLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHouseFLFActionPerformed(evt);
            }
        });
        jcbHouseFLF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbHouseFLFKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpFemaleLayout = new javax.swing.GroupLayout(jpFemale);
        jpFemale.setLayout(jpFemaleLayout);
        jpFemaleLayout.setHorizontalGroup(
            jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFemaleLayout.createSequentialGroup()
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFemaleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFemaleLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFemaleLayout.createSequentialGroup()
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFemale1)
                                    .addComponent(jLabelFemale3)
                                    .addComponent(jLabelFemale4)
                                    .addComponent(jLabelFemale2))
                                .addGap(18, 18, 18)
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFLFDeadT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLFDeadAP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLFCullAP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpFemaleLayout.createSequentialGroup()
                                .addComponent(jLabelFemale7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFLFInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFemaleLayout.createSequentialGroup()
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFemale5)
                                    .addComponent(jLabelFemale6))
                                .addGap(18, 18, 18)
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFLFDeadVac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLFCullT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpFemaleLayout.createSequentialGroup()
                        .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFemaleLayout.createSequentialGroup()
                                .addComponent(jLabelCode1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFemaleLayout.createSequentialGroup()
                                .addGap(0, 45, Short.MAX_VALUE)
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelHouse1)
                                    .addComponent(jLabelMO))
                                .addGap(9, 9, 9)))
                        .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbHouseFLF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMOFLF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpFemaleLayout.setVerticalGroup(
            jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFemaleLayout.createSequentialGroup()
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFemaleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextMOFLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMO)))
                    .addComponent(jLabelCode1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHouse1)
                    .addComponent(jcbHouseFLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale1))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFDeadAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale2))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFCullAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale3))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFDeadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale4))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFCullT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale5))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFDeadVac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale6))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFemale1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFLMDeadAP.setText("0");
        jTextFLMDeadAP.setEnabled(false);
        jTextFLMDeadAP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMDeadAPFocusLost(evt);
            }
        });

        jTextFLMCullAP.setText("0");
        jTextFLMCullAP.setEnabled(false);
        jTextFLMCullAP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMCullAPFocusLost(evt);
            }
        });

        jTextFLMDeadT.setText("0");
        jTextFLMDeadT.setEnabled(false);
        jTextFLMDeadT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMDeadTFocusLost(evt);
            }
        });

        jTextFLMCullT.setText("0");
        jTextFLMCullT.setEnabled(false);
        jTextFLMCullT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMCullTFocusLost(evt);
            }
        });

        jLabelFemale8.setText("ทั้งหมด :");

        jLabelFemale9.setText("ตายจากต้นทาง :");

        jLabelFemale10.setText("พิการจากต้นทาง :");

        jLabelFemale11.setText("ตายระหว่างขนส่ง :");

        jLabelFemale12.setText("พิการระหว่างขนส่ง :");

        jLabelFemale13.setText("ตายระหว่างวัคซีน :");

        jLabelFemale14.setText("ส่งเข้าฟาร์ม :");

        jTextFLMInsert.setText("0");
        jTextFLMInsert.setEnabled(false);
        jTextFLMInsert.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMInsertFocusLost(evt);
            }
        });

        jTextFLMDeadVac.setText("0");
        jTextFLMDeadVac.setEnabled(false);
        jTextFLMDeadVac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMDeadVacFocusLost(evt);
            }
        });

        jTextFLMTotal.setText("0");
        jTextFLMTotal.setEnabled(false);
        jTextFLMTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMTotalFocusLost(evt);
            }
        });

        jLabelCode3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode3.setForeground(java.awt.Color.red);
        jLabelCode3.setText("Male");

        jLabel2.setText("________________________________________________");

        javax.swing.GroupLayout jpFemale1Layout = new javax.swing.GroupLayout(jpFemale1);
        jpFemale1.setLayout(jpFemale1Layout);
        jpFemale1Layout.setHorizontalGroup(
            jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFemale1Layout.createSequentialGroup()
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFemale1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFemale1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFemale1Layout.createSequentialGroup()
                                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFemale8)
                                    .addComponent(jLabelFemale10)
                                    .addComponent(jLabelFemale11)
                                    .addComponent(jLabelFemale9))
                                .addGap(18, 18, 18)
                                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFLMDeadT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLMDeadAP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLMCullAP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpFemale1Layout.createSequentialGroup()
                                .addComponent(jLabelFemale14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFLMInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFemale1Layout.createSequentialGroup()
                                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFemale12)
                                    .addComponent(jLabelFemale13))
                                .addGap(18, 18, 18)
                                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFLMDeadVac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLMCullT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabelCode3))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jpFemale1Layout.setVerticalGroup(
            jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFemale1Layout.createSequentialGroup()
                .addComponent(jLabelCode3)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale8))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMDeadAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale9))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMCullAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale10))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMDeadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale11))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMCullT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale12))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMDeadVac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale13))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFMLLayout = new javax.swing.GroupLayout(jPanelFML);
        jPanelFML.setLayout(jPanelFMLLayout);
        jPanelFMLLayout.setHorizontalGroup(
            jPanelFMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFMLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFemale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpFemale1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelFMLLayout.setVerticalGroup(
            jPanelFMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFMLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpFemale1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("PS Grower", null, jPanelFML, "");

        jcbFlight.setText("2.สนามบิน");
        jcbFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFlightActionPerformed(evt);
            }
        });

        jPanelTransport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCode2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode2.setForeground(java.awt.Color.red);
        jLabelCode2.setText("Transport");

        jTextCar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCar1ActionPerformed(evt);
            }
        });

        jLabelCar1.setText("ทะเบียนรถ #1 :");

        jTextCar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCar2ActionPerformed(evt);
            }
        });

        jLabelCar2.setText("ทะเบียนรถ #2 :");

        jLabelST1.setText("เวลาเริ่ม :");

        jLabelST2.setText("เวลาเริ่ม :");

        jLabelAR2.setText("เวลาถึงฟาร์ม :");

        jLabelTem1.setText("อุณหภูมิ (ระหว่างส่ง) :");

        jTextTem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTem1ActionPerformed(evt);
            }
        });

        jLabelTem2.setText("อุณหภูมิ (ระหว่างส่ง) :");

        jTextTem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTem2ActionPerformed(evt);
            }
        });

        jLabelAR1.setText("เวลาถึงฟาร์ม :");

        jsST1.setEnabled(false);

        jsAR1.setEnabled(false);

        jsST2.setEnabled(false);

        jsAR2.setEnabled(false);

        javax.swing.GroupLayout jPanelTransportLayout = new javax.swing.GroupLayout(jPanelTransport);
        jPanelTransport.setLayout(jPanelTransportLayout);
        jPanelTransportLayout.setHorizontalGroup(
            jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelCar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextCar1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelCar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextCar2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelST2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsST2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelST1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsST1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelAR2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelAR1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelTem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTem1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelTem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTem2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTransportLayout.createSequentialGroup()
                .addComponent(jLabelCode2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelTransportLayout.setVerticalGroup(
            jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransportLayout.createSequentialGroup()
                .addComponent(jLabelCode2)
                .addGap(13, 13, 13)
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCar1)
                            .addComponent(jTextCar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCar2)
                            .addComponent(jTextCar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTem1)
                            .addComponent(jTextTem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTem2)
                            .addComponent(jTextTem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAR1)
                            .addComponent(jsST1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelST1)
                            .addComponent(jsAR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAR2)
                            .addComponent(jLabelST2)
                            .addComponent(jsST2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsAR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jLabelFlock.setText("Flock Code : ");

        jLabelFarm.setText("Farm Code :");

        jLabelFlockSTDate.setText("Receivied Date :");

        jLabelHouse.setText("House Code :");

        jXDateReceivied.setEnabled(false);

        jcbFarm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Farm" }));
        jcbFarm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbFarmKeyPressed(evt);
            }
        });

        jTextFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFlightActionPerformed(evt);
            }
        });

        jcbHouse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select House" }));
        jcbHouse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbHouseKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFlockSTDate)
                            .addComponent(jLabelFarm))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelHouse))
                            .addComponent(jXDateReceivied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbHatchery)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbFlight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelFlock)
                                .addGap(18, 18, 18)
                                .addComponent(jcbFlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanelTransport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonSave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonClose))
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 419, Short.MAX_VALUE)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 419, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFlockSTDate)
                            .addComponent(jXDateReceivied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFarm)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelHouse)
                                .addComponent(jcbHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelFlock)
                                .addComponent(jcbFlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStart)
                            .addComponent(jcbHatchery)
                            .addComponent(jcbFlight))))
                .addGap(17, 17, 17)
                .addComponent(jPanelTransport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 385, Short.MAX_VALUE)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 386, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GetData() {
        Flock = BRData01.vDUCK_FLOCK;
        House = BRData01.vDUCK_HOUSE;
        DateRec = BRData01.vDUCK_DATEREC;
        MO = BRData01.vDUCK_MO;
        Table = BRData01.vDUCK_Type;
        Farm = BRData01.vDUCK_FARM;
        pulldata();
    }

    private void pulldata() {
        List<String> getListItemDuckForChange = cld.GetDuckDataForChange(Flock, House, DateRec, MO, Table, Farm);
        for (int i = 0; i < getListItemDuckForChange.size(); i++) {
            String[] CheckItemDuckDetail = getListItemDuckForChange.get(i).split(";");
            String dateFormat = "dd/MM/yyyy";
            SimpleDateFormat sdf = new SimpleDateFormat(dateFormat, Locale.ENGLISH);
            String dateString = CheckItemDuckDetail[1].trim();
            Date date = null;
            try {
                date = sdf.parse(dateString);
            } catch (ParseException ex) {
                Logger.getLogger(BRDuck03.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                date = sdf.parse(dateString);
//             Date dateObject = Date.from(dateObject.atStartOfDay(ZoneId.systemDefault()).toInstant());
            } catch (ParseException ex) {
                Logger.getLogger(BRDuck03.class.getName()).log(Level.SEVERE, null, ex);
            }

            jXDateReceivied.setDate(date);
            jcbHouse.setSelectedItem(CheckItemDuckDetail[2].trim());
            jcbHouseFLF.setSelectedItem(CheckItemDuckDetail[2].trim());
//            jcbHouseFLM.setSelectedItem(CheckItemDuckDetail[2].trim());
            jcbFlock.setSelectedItem(CheckItemDuckDetail[3].trim());
            jTextMOFLF.setText(MO);
//            jTextMOFLM.setText(MO);
            jTextMOFLF.setForeground(Color.blue);
//            jTextMOFLM.setForeground(Color.blue);
            jcbHouse.setEnabled(false);
            jTextFlight.setEnabled(false);
            jTextFlight.setText(CheckItemDuckDetail[5].trim());
            jTextFLFTotal.setText(CheckItemDuckDetail[14].trim());
            jTextFLMTotal.setText(CheckItemDuckDetail[15].trim());
            jTextFLFDeadAP.setText(CheckItemDuckDetail[16].trim());
            jTextFLMDeadAP.setText(CheckItemDuckDetail[17].trim());
            jTextFLFCullAP.setText(CheckItemDuckDetail[18].trim());
            jTextFLMCullAP.setText(CheckItemDuckDetail[19].trim());
            jTextFLFDeadT.setText(CheckItemDuckDetail[20].trim());
            jTextFLMDeadT.setText(CheckItemDuckDetail[21].trim());
            jTextFLFCullT.setText(CheckItemDuckDetail[22].trim());
            jTextFLMCullT.setText(CheckItemDuckDetail[23].trim());
            jTextFLFDeadVac.setText(CheckItemDuckDetail[24].trim());
            jTextFLMDeadVac.setText(CheckItemDuckDetail[25].trim());
            jTextFLFInsert.setText(CheckItemDuckDetail[26].trim());
            jTextFLMInsert.setText(CheckItemDuckDetail[27].trim());
//            jTextMOFLF.setText(CheckItemDuckDetail[29].trim());
//            jTextMOFLM.setText(CheckItemDuckDetail[28].trim());
            jTextTem1.setText(CheckItemDuckDetail[12].trim());
            jTextTem2.setText(CheckItemDuckDetail[13].trim());
            jTextCar1.setText(CheckItemDuckDetail[6].trim());
            jTextCar2.setText(CheckItemDuckDetail[7].trim());
            String Delivertype = CheckItemDuckDetail[4].trim();
            if (Delivertype.equals("1")) {
                jcbHatchery.setSelected(true);
            } else if (Delivertype.equals("2")) {
                jcbFlight.setSelected(false);
            }
//                CheckItemDuckDetail[0].trim(),
//                CheckItemDuckDetail[1].trim(),
//                CheckItemDuckDetail[2].trim(),
//                CheckItemDuckDetail[3].trim(),
//                CheckItemDuckDetail[4].trim(),
//                CheckItemDuckDetail[5].trim(),
//                CheckItemDuckDetail[6].trim(),
//                CheckItemDuckDetail[7].trim(),
//                CheckItemDuckDetail[8].trim(),
//                CheckItemDuckDetail[9].trim(),
//                CheckItemDuckDetail[10].trim(),
//                CheckItemDuckDetail[11].trim(),
//                CheckItemDuckDetail[12].trim(),
//                CheckItemDuckDetail[13].trim(),
//                CheckItemDuckDetail[14].trim(),
//                CheckItemDuckDetail[15].trim(),
//                CheckItemDuckDetail[16].trim(),
//                CheckItemDuckDetail[17].trim()
//                CheckItemDuckDetail[18].trim()

        }
    }


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jcbFlockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbFlockKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFlockKeyPressed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveMouseClicked

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        String from = "0";
        if (jcbHatchery.isSelected()) {
            from = "1";
        } else if (jcbFlight.isSelected()) {
            from = "2";
        }
        String[] getHouseFLF = jcbHouseFLF.getSelectedItem().toString().split(":");
        String vHouseFLF = getHouseFLF[0].trim();
        String[] getFlock = jcbFlock.getSelectedItem().toString().split(":");
        String vFlock = getFlock[0].trim();
        cid.UpdateDuck(Table, from, jTextCar1.getText(),
                jTextCar2.getText(), jTextMOFLF.getText(),
                jTextTem1.getText(), jTextTem2.getText(),
                sdf.format(jXDateReceivied.getDate()), vHouseFLF, vFlock, BRLogin.vDuckBreed, BRLogin.vFarm);
        JOptionPane.showMessageDialog(null, "Data Changed Completed");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jcbHatcheryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHatcheryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHatcheryActionPerformed

    private void jTextFLFDeadAPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFDeadAPFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFLFDeadAPFocusLost

    private void jTextFLFCullAPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFCullAPFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFLFCullAPFocusLost

    private void jTextFLFDeadTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFDeadTFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFLFDeadTFocusLost

    private void jTextFLFCullTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFCullTFocusLost

    }//GEN-LAST:event_jTextFLFCullTFocusLost

    private void jTextFLFInsertFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFInsertFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFLFInsertFocusLost

    private void jTextFLFDeadVacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFDeadVacFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFLFDeadVacFocusLost

    private void jTextFLFTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFTotalFocusLost
        // TODO add your handling code here
    }//GEN-LAST:event_jTextFLFTotalFocusLost

    private void jTextMOFLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMOFLFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMOFLFActionPerformed

    private void jTextFLMDeadAPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMDeadAPFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFLMDeadAPFocusLost

    private void jTextFLMCullAPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMCullAPFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFLMCullAPFocusLost

    private void jTextFLMDeadTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMDeadTFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFLMDeadTFocusLost

    private void jTextFLMCullTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMCullTFocusLost

    }//GEN-LAST:event_jTextFLMCullTFocusLost

    private void jTextFLMInsertFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMInsertFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFLMInsertFocusLost

    private void jTextFLMDeadVacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMDeadVacFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFLMDeadVacFocusLost

    private void jTextFLMTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMTotalFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFLMTotalFocusLost

    private void jPanelFMLComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelFMLComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanelFMLComponentShown

    private void jcbFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFlightActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jcbFlightActionPerformed

    private void jTextCar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCar1ActionPerformed

    private void jTextCar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCar2ActionPerformed

    private void jTextTem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTem1ActionPerformed

    private void jTextTem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTem2ActionPerformed

    private void jcbFarmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbFarmKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFarmKeyPressed

    private void jTextFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFlightActionPerformed

    private void jcbHouseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbHouseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHouseKeyPressed

    private void jcbHouseFLFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbHouseFLFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHouseFLFKeyPressed

    private void jcbHouseFLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHouseFLFActionPerformed
        // TODO add your handling code here:
        String[] getHouseFLF = jcbHouseFLF.getSelectedItem().toString().split(":");
        String vHouseFLF = getHouseFLF[0].trim();
        jTextMOFLF.setText(crd.CheckLastMO(BRLogin.vFarm, BRLogin.vDuckBreed, vHouseFLF));
        jTextMOFLF.setForeground(Color.blue);
    }//GEN-LAST:event_jcbHouseFLFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAR1;
    private javax.swing.JLabel jLabelAR2;
    private javax.swing.JLabel jLabelCar1;
    private javax.swing.JLabel jLabelCar2;
    private javax.swing.JLabel jLabelCode1;
    private javax.swing.JLabel jLabelCode2;
    private javax.swing.JLabel jLabelCode3;
    private javax.swing.JLabel jLabelFarm;
    private javax.swing.JLabel jLabelFemale1;
    private javax.swing.JLabel jLabelFemale10;
    private javax.swing.JLabel jLabelFemale11;
    private javax.swing.JLabel jLabelFemale12;
    private javax.swing.JLabel jLabelFemale13;
    private javax.swing.JLabel jLabelFemale14;
    private javax.swing.JLabel jLabelFemale2;
    private javax.swing.JLabel jLabelFemale3;
    private javax.swing.JLabel jLabelFemale4;
    private javax.swing.JLabel jLabelFemale5;
    private javax.swing.JLabel jLabelFemale6;
    private javax.swing.JLabel jLabelFemale7;
    private javax.swing.JLabel jLabelFemale8;
    private javax.swing.JLabel jLabelFemale9;
    private javax.swing.JLabel jLabelFlock;
    private javax.swing.JLabel jLabelFlockSTDate;
    private javax.swing.JLabel jLabelHouse;
    private javax.swing.JLabel jLabelHouse1;
    private javax.swing.JLabel jLabelMO;
    private javax.swing.JLabel jLabelST1;
    private javax.swing.JLabel jLabelST2;
    private javax.swing.JLabel jLabelStart;
    private javax.swing.JLabel jLabelTem1;
    private javax.swing.JLabel jLabelTem2;
    private javax.swing.JPanel jPanelFML;
    private javax.swing.JPanel jPanelTransport;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextCar1;
    private javax.swing.JTextField jTextCar2;
    private javax.swing.JTextField jTextFLFCullAP;
    private javax.swing.JTextField jTextFLFCullT;
    private javax.swing.JTextField jTextFLFDeadAP;
    private javax.swing.JTextField jTextFLFDeadT;
    private javax.swing.JTextField jTextFLFDeadVac;
    private javax.swing.JTextField jTextFLFInsert;
    private javax.swing.JTextField jTextFLFTotal;
    private javax.swing.JTextField jTextFLMCullAP;
    private javax.swing.JTextField jTextFLMCullT;
    private javax.swing.JTextField jTextFLMDeadAP;
    private javax.swing.JTextField jTextFLMDeadT;
    private javax.swing.JTextField jTextFLMDeadVac;
    private javax.swing.JTextField jTextFLMInsert;
    private javax.swing.JTextField jTextFLMTotal;
    private javax.swing.JTextField jTextFlight;
    private javax.swing.JTextField jTextMOFLF;
    private javax.swing.JTextField jTextTem1;
    private javax.swing.JTextField jTextTem2;
    private org.jdesktop.swingx.JXDatePicker jXDateReceivied;
    private javax.swing.JComboBox jcbFarm;
    private javax.swing.JCheckBox jcbFlight;
    private javax.swing.JComboBox jcbFlock;
    private javax.swing.JCheckBox jcbHatchery;
    private javax.swing.JComboBox jcbHouse;
    private javax.swing.JComboBox jcbHouseFLF;
    private javax.swing.JPanel jpFemale;
    private javax.swing.JPanel jpFemale1;
    private javax.swing.JSpinner jsAR1;
    private javax.swing.JSpinner jsAR2;
    private javax.swing.JSpinner jsST1;
    private javax.swing.JSpinner jsST2;
    // End of variables declaration//GEN-END:variables

}
