/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BRFARM;

import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wattana
 */
public class BRFlock01 extends javax.swing.JFrame {

    public static String vStatus;
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    DefaultTableModel model;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy", Locale.US);
    final Date startDate = new Date();
    ClassReturnData crd = new ClassReturnData();
    ClassInsertData cid = new ClassInsertData();
    ClassListData cld = new ClassListData();

    /**
     * Creates new form M001Flock
     */
    public BRFlock01() {
        initComponents();
        this.setTitle("FAR_FLOCK : " + BRLogin.vDuckBreed + " " + BRLogin.vDuckBreedDesc + " : " + BRLogin.vFarm + " " + BRLogin.vFarmDesc);
        jXDateStart.setFormats(sdf);
        jXDateEnd.setFormats(sdf);
        jXDateWeek.setFormats(sdf);
        jXDateStart.setDate(new Date());
        jXDateWeek.setDate(new Date());
        jButtonUpdate.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClose = new javax.swing.JButton();
        jTextCode = new javax.swing.JTextField();
        jLabelCode = new javax.swing.JLabel();
        jLabelFlockSTDate = new javax.swing.JLabel();
        jLabelFlockEndDate = new javax.swing.JLabel();
        jButtonCreate = new javax.swing.JButton();
        jLabelBreed = new javax.swing.JLabel();
        jTextDesc = new javax.swing.JTextField();
        jLabelStat = new javax.swing.JLabel();
        jLabelSTWeek = new javax.swing.JLabel();
        jXDateStart = new org.jdesktop.swingx.JXDatePicker();
        jXDateEnd = new org.jdesktop.swingx.JXDatePicker();
        jXDateWeek = new org.jdesktop.swingx.JXDatePicker();
        jButtonUpdate = new javax.swing.JButton();
        jcbYes = new javax.swing.JCheckBox();
        jcbNo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FAR_FLOCK. CREATE");
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jTextCode.setSelectionEnd(2);

        jLabelCode.setForeground(java.awt.Color.red);
        jLabelCode.setText("Flock Code : *");

        jLabelFlockSTDate.setText("Flock Start Date :");

        jLabelFlockEndDate.setText("Flock End Date :");

        jButtonCreate.setText("Create");
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jLabelBreed.setText("Flock Desc :");

        jTextDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescActionPerformed(evt);
            }
        });

        jLabelStat.setText("Flock Status :");

        jLabelSTWeek.setText("Flock Start Week :");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jcbYes.setText("Yes");
        jcbYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbYesActionPerformed(evt);
            }
        });

        jcbNo.setText("No");
        jcbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCreate)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSTWeek)
                            .addComponent(jLabelStat)
                            .addComponent(jLabelBreed))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jXDateWeek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbYes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbNo)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jTextDesc))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFlockEndDate)
                            .addComponent(jLabelFlockSTDate)
                            .addComponent(jLabelCode))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCode)
                            .addComponent(jXDateStart, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                            .addComponent(jXDateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFlockSTDate)
                    .addComponent(jXDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFlockEndDate)
                    .addComponent(jXDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBreed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStat)
                    .addComponent(jcbYes)
                    .addComponent(jcbNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSTWeek)
                    .addComponent(jXDateWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonCreate)
                    .addComponent(jButtonUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        // TODO add your handling code here: 

        try {

            if (jTextCode.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Insert Flock Code");
                jTextCode.requestFocusInWindow();
            } else if (jcbYes.isSelected() == false && jcbNo.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Select Status");
                jcbYes.requestFocusInWindow();
            } else {
                String DateStart, DateEnd, DateWeek;

                if (jXDateStart.getDate() == null) {
                    DateStart = "";
                } else {
                    DateStart = sdf.format(jXDateStart.getDate());
                }

                if (jXDateEnd.getDate() == null) {
                    DateEnd = "";
                } else {
                    DateEnd = sdf.format(jXDateEnd.getDate());
                }

                if (jXDateWeek.getDate() == null) {
                    DateWeek = "";
                } else {
                    DateWeek = sdf.format(jXDateWeek.getDate());
                }

                String count = crd.CheckFlockDuplicate(BRLogin.vFarm, jTextCode.getText());

                if (Integer.valueOf(count) > 0) {
                    JOptionPane.showMessageDialog(null, jTextCode.getText() + " Data Already");
                } else {
                    cid.InsertFlock(jTextCode.getText(), BRLogin.vFarm, DateStart, DateEnd, jTextDesc.getText(), vStatus, DateWeek, BRLogin.vDuckBreed);
                    JOptionPane.showMessageDialog(null, "Insert Success");
                    BRData01.FrameOpen = "No";
                    this.setVisible(false);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            if ("Yes".equals(BRData01.OnChange)) {
                jTextCode.setText(BRData01.vFLOC_CODE);
                jXDateStart.setDate(sdf.parse(BRData01.vFLOC_STDATE));

                if ("".equals(BRData01.vFLOC_ENDATE)) {
                    jXDateEnd.setFormats(sdf);
                } else {
                    jXDateEnd.setDate(sdf.parse(BRData01.vFLOC_ENDATE));
                }

                jTextDesc.setText(BRData01.vFLOC_BREED);

                vStatus = BRData01.vFLOC_STATUS;
                if ("Yes".equals(vStatus)) {
                    jcbYes.setSelected(true);
                } else {
                    jcbNo.setSelected(true);
                }

                if (jcbYes.isSelected() == true) {
                    vStatus = "1";
                } else {
                    vStatus = "0";
                }

                jXDateWeek.setDate(sdf.parse(BRData01.vFLOC_STWEEK));
                jXDateStart.requestFocusInWindow();
                jTextCode.setEnabled(false);
                jButtonCreate.setVisible(false);
                jButtonUpdate.setVisible(true);
                BRData01.OnChange = "No";
            } else {
                jTextCode.requestFocusInWindow();
                jTextCode.setEnabled(true);
                jButtonCreate.setVisible(true);
                jButtonUpdate.setVisible(false);
                BRData01.OnCreate = "No";
            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    private void jTextDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        String DateStart,DateEnd,DateWeek;

        if (jXDateStart.getDate() == null) {
            DateStart = "";
        } else {
            DateStart = sdf.format(jXDateStart.getDate());
        }

        if (jXDateEnd.getDate() == null) {
            DateEnd = "";
        } else {
            DateEnd = sdf.format(jXDateEnd.getDate());
        }

        if (jXDateWeek.getDate() == null) {
            DateWeek = "";
        } else {
            DateWeek = sdf.format(jXDateWeek.getDate());
        }

        cid.UpdateFlock(jTextCode.getText(), BRLogin.vFarm, DateStart,DateEnd,jTextDesc.getText(), vStatus,DateWeek,BRLogin.vDuckBreed);
        JOptionPane.showMessageDialog(null, "Update Success");
        BRData01.FrameOpen = "No";
        this.setVisible(false);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jcbYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbYesActionPerformed
        // TODO add your handling code here:
        if (jcbYes.isSelected() == true) {
            vStatus = "1";
            jcbNo.setSelected(false);
        } else {
            vStatus = null;
        }
    }//GEN-LAST:event_jcbYesActionPerformed

    private void jcbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNoActionPerformed
        // TODO add your handling code here:
        if (jcbNo.isSelected() == true) {
            vStatus = "0";
            jcbYes.setSelected(false);
        } else {
            vStatus = null;
        }
    }//GEN-LAST:event_jcbNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BRFlock01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BRFlock01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BRFlock01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BRFlock01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BRFlock01().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelBreed;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelFlockEndDate;
    private javax.swing.JLabel jLabelFlockSTDate;
    private javax.swing.JLabel jLabelSTWeek;
    private javax.swing.JLabel jLabelStat;
    private javax.swing.JTextField jTextCode;
    private javax.swing.JTextField jTextDesc;
    private org.jdesktop.swingx.JXDatePicker jXDateEnd;
    private org.jdesktop.swingx.JXDatePicker jXDateStart;
    private org.jdesktop.swingx.JXDatePicker jXDateWeek;
    private javax.swing.JCheckBox jcbNo;
    private javax.swing.JCheckBox jcbYes;
    // End of variables declaration//GEN-END:variables

}
