/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BRFARM;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Wattana
 */
public class BRMain extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public BRMain() {
        initComponents();
        this.setTitle("BRFARM : " + BRLogin.vDuckBreed + " " + BRLogin.vDuckBreedDesc + " : " + BRLogin.vFarm + " " + BRLogin.vFarmDesc);
        if("CM".equals(BRLogin.vDuckBreed)){
            //Remove Data Select Option
            jMenuGrowerMT.setVisible(false);
            jMenuGrower.setVisible(false);
            jMenuLaying.setVisible(false);
            jMenuLayingMT.setVisible(false);
            //Remove select of of option for Report
            jMenuItem1.setVisible(false);
            jMenuItem5.setVisible(false);
        }
        else{
            //Remove Data Select Option
            jMenuItem20.setVisible(false);
            //Remove select of of option for Report
            jMenuItem21.setVisible(false);
            jMenuItem22.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmMasterData = new javax.swing.JMenu();
        jMenuData = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuGrower = new javax.swing.JMenuItem();
        jMenuLaying = new javax.swing.JMenuItem();
        jMenuGrowerMT = new javax.swing.JMenuItem();
        jMenuLayingMT = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jmTransaction = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jmInventory = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jmReport = new javax.swing.JMenu();
        jMenuDataStd = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jmManagement = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BRFARM");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jmMasterData.setText("Master Data :");
        jmMasterData.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jMenuData.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuData.setText("(BF01M001) Data");
        jMenuData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDataActionPerformed(evt);
            }
        });
        jmMasterData.add(jMenuData);

        jMenuItem19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem19.setText("(BR01M002) Egg by House");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jmMasterData.add(jMenuItem19);

        jMenuGrower.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuGrower.setText("(BF01E001) Grower Setting");
        jMenuGrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGrowerActionPerformed(evt);
            }
        });
        jmMasterData.add(jMenuGrower);

        jMenuLaying.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuLaying.setText("(BF01E003) Laying Setting");
        jMenuLaying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLayingActionPerformed(evt);
            }
        });
        jmMasterData.add(jMenuLaying);

        jMenuGrowerMT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuGrowerMT.setText("(BF01E004) Grower Moulting Setting");
        jMenuGrowerMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGrowerMTActionPerformed(evt);
            }
        });
        jmMasterData.add(jMenuGrowerMT);

        jMenuLayingMT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuLayingMT.setText("(BF01E005) Laying Moulting Setting");
        jMenuLayingMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLayingMTActionPerformed(evt);
            }
        });
        jmMasterData.add(jMenuLayingMT);

        jMenuItem20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem20.setText("(BR01E006) Meat Duck Setting");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jmMasterData.add(jMenuItem20);

        jMenuBar1.add(jmMasterData);

        jmTransaction.setText("Transaction :");
        jmTransaction.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem2.setText("(BF01E002) Daily Issue");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmTransaction.add(jMenuItem2);

        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem7.setText("(BF01P007) Egg Transfer");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jmTransaction.add(jMenuItem7);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem3.setText("(BF01E008) Description Egg Transfer");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmTransaction.add(jMenuItem3);

        jMenuItem18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem18.setText("(BF01E009) Adjust Stock");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jmTransaction.add(jMenuItem18);

        jMenuBar1.add(jmTransaction);

        jmInventory.setText("Inventory : ");
        jmInventory.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem12.setText("(BF01D001) Balance Stock");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jmInventory.add(jMenuItem12);

        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem4.setText("(BF01D003) Balance Stock by Lot Number");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmInventory.add(jMenuItem4);

        jMenuItem13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem13.setText("(BF01D002) History Transection");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jmInventory.add(jMenuItem13);

        jMenuBar1.add(jmInventory);

        jmReport.setText("Report :");
        jmReport.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jmReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmReportActionPerformed(evt);
            }
        });

        jMenuDataStd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuDataStd.setText("(BR01R001) Data Standard");
        jMenuDataStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDataStdActionPerformed(evt);
            }
        });
        jmReport.add(jMenuDataStd);

        jMenuItem9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem9.setText("(BR01R002) M3 Transfer Report");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem9);

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem1.setText("(BR01R003) Daily Report");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem1);

        jMenuItem21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem21.setText("(BR01R003) Daily Report (Commercial)");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem21);

        jMenuItem5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem5.setText("(BR01R004) Weekly Report");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem5);

        jMenuItem22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem22.setText("(BR01R004) Weekly Report (Commercial)");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem22);

        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem6.setText("(BR01R005) Inventory Balance Report");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem6);

        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem8.setText("(BR01R009) Egg Transfer Report");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem8);

        jMenuItem10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem10.setText("(BR01R010) Egg Transfer Description Report");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem11.setText("(BR01R012) Egg From Processing Report");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem11);

        jMenuItem14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem14.setText("(BR01R013) Medicine and Vaccine");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem15.setText("(BR01R018) Performance Report");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem16.setText("(BR01R029) Duck Health Report");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jmReport.add(jMenuItem16);

        jMenuBar1.add(jmReport);

        jmManagement.setText("Management :");
        jmManagement.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jMenuItem17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jMenuItem17.setText("(BR01U001) User");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jmManagement.add(jMenuItem17);

        jMenuBar1.add(jmManagement);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        setBounds(10, 20, 837, 147);
    }// </editor-fold>//GEN-END:initComponents

    private void jmReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmReportActionPerformed

    private void jMenuDataStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDataStdActionPerformed
        // TODO add your handling code here:
        new BR01R001().setVisible(true);
    }//GEN-LAST:event_jMenuDataStdActionPerformed

    private void jMenuGrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGrowerActionPerformed
        // TODO add your handling code here:
        if ("PS".equals(BRLogin.vDuckBreed)) {
            new BRPS01G().setVisible(true);
        } else {
            new BRGP01G().setVisible(true);
        }
    }//GEN-LAST:event_jMenuGrowerActionPerformed

    private void jMenuLayingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLayingActionPerformed
        // TODO add your handling code here:
        if ("PS".equals(BRLogin.vDuckBreed)) {
            new BRPS03L().setVisible(true);
        } else {
            new BRGP03L().setVisible(true);
        }
    }//GEN-LAST:event_jMenuLayingActionPerformed

    private void jMenuGrowerMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGrowerMTActionPerformed
        // TODO add your handling code here:
        if ("PS".equals(BRLogin.vDuckBreed)) {
            new BRPS04GMT().setVisible(true);
        } else {
            new BRGP04GMT().setVisible(true);
        }
    }//GEN-LAST:event_jMenuGrowerMTActionPerformed

    private void jMenuLayingMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLayingMTActionPerformed
        // TODO add your handling code here:
        if ("PS".equals(BRLogin.vDuckBreed)) {
            new BRPS05LMT().setVisible(true);
        } else {
            new BRGP05LMT().setVisible(true);
        }
    }//GEN-LAST:event_jMenuLayingMTActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new BRIssueStock01().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new BRDescEggTrans02().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDataActionPerformed
        // TODO add your handling code here:
        new BRData01().setVisible(true);
    }//GEN-LAST:event_jMenuDataActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new BRStock01().setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new BRTrans01().setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new BREggTrans01().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new BRStockLot01().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new BR01R003().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new BR01R004().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new BR01R005().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new BR01R009().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new BR01R002().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new BR01R010().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new BR01R012().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        new BR01R013().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        new BR01R018().setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        new BR01R029().setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if ("ADMIN".equals(BRLogin.vAuth)) {
            jmManagement.setVisible(true);
        } else {
            jmManagement.setVisible(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        new BRUser01().setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        new BRAdjustStock01().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        new BRItemHouse01().setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
         new BRCM01M().setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        new BR01R003_CM().setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        new BR01R004_CM().setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BRMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuData;
    private javax.swing.JMenuItem jMenuDataStd;
    private javax.swing.JMenuItem jMenuGrower;
    private javax.swing.JMenuItem jMenuGrowerMT;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuLaying;
    private javax.swing.JMenuItem jMenuLayingMT;
    private javax.swing.JMenu jmInventory;
    private javax.swing.JMenu jmManagement;
    private javax.swing.JMenu jmMasterData;
    private javax.swing.JMenu jmReport;
    private javax.swing.JMenu jmTransaction;
    // End of variables declaration//GEN-END:variables
}
