/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BRFARM;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Wattana
 */
public class BRPS05LMT extends javax.swing.JFrame {

    int FLFTotal, FLFDeadAP, FLFCullAP, FLFDeadT, FLFCullT, FLFDeadVac, FLFSumTotal;
    int FLMTotal, FLMDeadAP, FLMCullAP, FLMDeadT, FLMCullT, FLMDeadVac, FLMSumTotal;
    int MLFTotal, MLFDeadAP, MLFCullAP, MLFDeadT, MLFCullT, MLFDeadVac, MLFSumTotal;
    int MLMTotal, MLMDeadAP, MLMCullAP, MLMDeadT, MLMCullT, MLMDeadVac, MLMSumTotal;
    String vFrom = "0";
    String JPanel = "FML";
    String StsInsertDuck = "No";
    String StsTransferDuck = "No";
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    DefaultTableModel model;
    ClassReturnData crd = new ClassReturnData();
    ClassInsertData cid = new ClassInsertData();
    ClassListData cld = new ClassListData();
    Calendar cal = Calendar.getInstance();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy", Locale.US);
    SimpleDateFormat stf = new SimpleDateFormat("HH:mm a");
    final Date startDate = new Date();
    SpinnerDateModel sdmST1 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    SpinnerDateModel sdmST2 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    SpinnerDateModel sdmAR1 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    SpinnerDateModel sdmAR2 = new SpinnerDateModel(startDate, null, null, Calendar.HOUR_OF_DAY);
    JSpinner spnST1 = new JSpinner(sdmST1);
    JSpinner spnST2 = new JSpinner(sdmST2);
    JSpinner spnAR1 = new JSpinner(sdmAR1);
    JSpinner spnAR2 = new JSpinner(sdmAR2);
    JSpinner.DateEditor dedST1 = new JSpinner.DateEditor(spnST1, "HH:mm a");
    JSpinner.DateEditor dedST2 = new JSpinner.DateEditor(spnST2, "HH:mm a");
    JSpinner.DateEditor dedAR1 = new JSpinner.DateEditor(spnAR1, "HH:mm a");
    JSpinner.DateEditor dedAR2 = new JSpinner.DateEditor(spnAR2, "HH:mm a");

    /**
     * Creates new form M001Farm
     */
    public BRPS05LMT() {
        initComponents();
        this.setTitle("BR01E003L. LAYING SETTING : " + BRLogin.vDuckBreed + " " + BRLogin.vDuckBreedDesc + " : " + BRLogin.vFarm + " " + BRLogin.vFarmDesc);
        jcbFarm.setModel(new DefaultComboBoxModel(cld.GetResultFarmDesc(BRLogin.vFarm).toArray()));
        jcbHouse.setModel(new DefaultComboBoxModel(cld.GetResultHouseDesc(BRLogin.vFarm, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll).toArray()));
        jcbFlock.setModel(new DefaultComboBoxModel(cld.GetResultFlockDesc(BRLogin.vFarm, BRLogin.vDuckBreed).toArray()));
        jcbHouseFLF.setModel(new DefaultComboBoxModel(cld.GetResultHouseDesc(BRLogin.vFarm, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll).toArray()));
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        Date startTime = cal.getTime();
        jXDateReceivied.setFormats(sdf);
        jXDateReceivied.setDate(new Date());
        jsST1.setModel(sdmST1);
        jsST1.setEditor(dedST1);
        jsST2.setModel(sdmST2);
        jsST2.setEditor(dedST2);
        jsAR1.setModel(sdmAR1);
        jsAR1.setEditor(dedAR1);
        jsAR2.setModel(sdmAR2);
        jsAR2.setEditor(dedAR2);
        jsST1.setValue(startTime);
        jsST2.setValue(startTime);
        jsAR1.setValue(startTime);
        jsAR2.setValue(startTime);
        jcbFarm.setSelectedIndex(1);
        jcbHouse.setEnabled(false);
        jTextFlight.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLabelFlock = new javax.swing.JLabel();
        jLabelFarm = new javax.swing.JLabel();
        jLabelFlockSTDate = new javax.swing.JLabel();
        jLabelHouse = new javax.swing.JLabel();
        jXDateReceivied = new org.jdesktop.swingx.JXDatePicker();
        jcbFarm = new javax.swing.JComboBox();
        jTextFlight = new javax.swing.JTextField();
        jLabelStart = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPanelTransport = new javax.swing.JPanel();
        jLabelCode2 = new javax.swing.JLabel();
        jTextCar1 = new javax.swing.JTextField();
        jLabelCar1 = new javax.swing.JLabel();
        jTextCar2 = new javax.swing.JTextField();
        jLabelCar2 = new javax.swing.JLabel();
        jLabelST1 = new javax.swing.JLabel();
        jLabelST2 = new javax.swing.JLabel();
        jLabelAR2 = new javax.swing.JLabel();
        jLabelTem1 = new javax.swing.JLabel();
        jTextTem1 = new javax.swing.JTextField();
        jLabelTem2 = new javax.swing.JLabel();
        jTextTem2 = new javax.swing.JTextField();
        jLabelAR1 = new javax.swing.JLabel();
        jsST1 = new javax.swing.JSpinner();
        jsAR1 = new javax.swing.JSpinner();
        jsST2 = new javax.swing.JSpinner();
        jsAR2 = new javax.swing.JSpinner();
        jcbHouse = new javax.swing.JComboBox();
        jcbFlock = new javax.swing.JComboBox();
        jcbHatchery = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelFML = new javax.swing.JPanel();
        jpFemale = new javax.swing.JPanel();
        jTextFLFDeadAP = new javax.swing.JTextField();
        jTextFLFCullAP = new javax.swing.JTextField();
        jTextFLFDeadT = new javax.swing.JTextField();
        jTextFLFCullT = new javax.swing.JTextField();
        jLabelFemale1 = new javax.swing.JLabel();
        jLabelFemale2 = new javax.swing.JLabel();
        jLabelFemale3 = new javax.swing.JLabel();
        jLabelFemale4 = new javax.swing.JLabel();
        jLabelFemale5 = new javax.swing.JLabel();
        jLabelFemale6 = new javax.swing.JLabel();
        jLabelFemale7 = new javax.swing.JLabel();
        jTextFLFInsert = new javax.swing.JTextField();
        jTextFLFDeadVac = new javax.swing.JTextField();
        jTextFLFTotal = new javax.swing.JTextField();
        jLabelCode1 = new javax.swing.JLabel();
        jLabelMO = new javax.swing.JLabel();
        jTextMOFLF = new javax.swing.JTextField();
        jButtonSendMOFMF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelHouse1 = new javax.swing.JLabel();
        jcbHouseFLF = new javax.swing.JComboBox();
        jpFemale1 = new javax.swing.JPanel();
        jTextFLMDeadAP = new javax.swing.JTextField();
        jTextFLMCullAP = new javax.swing.JTextField();
        jTextFLMDeadT = new javax.swing.JTextField();
        jTextFLMCullT = new javax.swing.JTextField();
        jLabelFemale8 = new javax.swing.JLabel();
        jLabelFemale9 = new javax.swing.JLabel();
        jLabelFemale10 = new javax.swing.JLabel();
        jLabelFemale11 = new javax.swing.JLabel();
        jLabelFemale12 = new javax.swing.JLabel();
        jLabelFemale13 = new javax.swing.JLabel();
        jLabelFemale14 = new javax.swing.JLabel();
        jTextFLMInsert = new javax.swing.JTextField();
        jTextFLMDeadVac = new javax.swing.JTextField();
        jTextFLMTotal = new javax.swing.JTextField();
        jLabelCode3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbFlight = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PS01E001. PS GROWER SETTING");
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelFlock.setText("Flock Code : ");

        jLabelFarm.setText("Farm Code :");

        jLabelFlockSTDate.setText("Receivied Date :");

        jLabelHouse.setText("House Code :");

        jcbFarm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Farm" }));
        jcbFarm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbFarmKeyPressed(evt);
            }
        });

        jTextFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFlightActionPerformed(evt);
            }
        });

        jLabelStart.setText("ต้นทาง :");

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonSave.setText("Transfers DOD");
        jButtonSave.setToolTipText("");
        jButtonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseClicked(evt);
            }
        });
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jPanelTransport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCode2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode2.setForeground(java.awt.Color.red);
        jLabelCode2.setText("Transport");

        jTextCar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCar1ActionPerformed(evt);
            }
        });

        jLabelCar1.setText("ทะเบียนรถ #1 :");

        jTextCar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCar2ActionPerformed(evt);
            }
        });

        jLabelCar2.setText("ทะเบียนรถ #2 :");

        jLabelST1.setText("เวลาเริ่ม :");

        jLabelST2.setText("เวลาเริ่ม :");

        jLabelAR2.setText("เวลาถึงฟาร์ม :");

        jLabelTem1.setText("อุณหภูมิ (ระหว่างส่ง) :");

        jTextTem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTem1ActionPerformed(evt);
            }
        });

        jLabelTem2.setText("อุณหภูมิ (ระหว่างส่ง) :");

        jTextTem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTem2ActionPerformed(evt);
            }
        });

        jLabelAR1.setText("เวลาถึงฟาร์ม :");

        javax.swing.GroupLayout jPanelTransportLayout = new javax.swing.GroupLayout(jPanelTransport);
        jPanelTransport.setLayout(jPanelTransportLayout);
        jPanelTransportLayout.setHorizontalGroup(
            jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelCar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextCar1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelCar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextCar2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelST2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsST2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelST1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsST1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelAR2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelAR1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelTem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTem1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addComponent(jLabelTem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTem2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTransportLayout.createSequentialGroup()
                .addComponent(jLabelCode2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelTransportLayout.setVerticalGroup(
            jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransportLayout.createSequentialGroup()
                .addComponent(jLabelCode2)
                .addGap(13, 13, 13)
                .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCar1)
                            .addComponent(jTextCar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCar2)
                            .addComponent(jTextCar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTem1)
                            .addComponent(jTextTem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTem2)
                            .addComponent(jTextTem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTransportLayout.createSequentialGroup()
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAR1)
                            .addComponent(jsST1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelST1)
                            .addComponent(jsAR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAR2)
                            .addComponent(jLabelST2)
                            .addComponent(jsST2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsAR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jcbHouse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select House" }));
        jcbHouse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbHouseKeyPressed(evt);
            }
        });

        jcbFlock.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Flock" }));
        jcbFlock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbFlockKeyPressed(evt);
            }
        });

        jcbHatchery.setText("1.โรงฟัก");
        jcbHatchery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHatcheryActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jPanelFML.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFML.setToolTipText("");
        jPanelFML.setName(""); // NOI18N
        jPanelFML.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelFMLComponentShown(evt);
            }
        });

        jpFemale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpFemale.setToolTipText("");

        jTextFLFDeadAP.setText("0");
        jTextFLFDeadAP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFDeadAPFocusLost(evt);
            }
        });

        jTextFLFCullAP.setText("0");
        jTextFLFCullAP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFCullAPFocusLost(evt);
            }
        });

        jTextFLFDeadT.setText("0");
        jTextFLFDeadT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFDeadTFocusLost(evt);
            }
        });

        jTextFLFCullT.setText("0");
        jTextFLFCullT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFCullTFocusLost(evt);
            }
        });

        jLabelFemale1.setText("ทั้งหมด :");

        jLabelFemale2.setText("ตายจากต้นทาง :");

        jLabelFemale3.setText("พิการจากต้นทาง :");

        jLabelFemale4.setText("ตายระหว่างขนส่ง :");

        jLabelFemale5.setText("พิการระหว่างขนส่ง :");

        jLabelFemale6.setText("ตายระหว่างวัคซีน :");

        jLabelFemale7.setText("ส่งเข้าฟาร์ม :");

        jTextFLFInsert.setText("0");
        jTextFLFInsert.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFInsertFocusLost(evt);
            }
        });

        jTextFLFDeadVac.setText("0");
        jTextFLFDeadVac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFDeadVacFocusLost(evt);
            }
        });

        jTextFLFTotal.setText("0");
        jTextFLFTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLFTotalFocusLost(evt);
            }
        });

        jLabelCode1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode1.setForeground(java.awt.Color.red);
        jLabelCode1.setText("Female");

        jLabelMO.setText("MO No. :");

        jTextMOFLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMOFLFActionPerformed(evt);
            }
        });

        jButtonSendMOFMF.setText("Send MO");
        jButtonSendMOFMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSendMOFMFMouseClicked(evt);
            }
        });
        jButtonSendMOFMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendMOFMFActionPerformed(evt);
            }
        });

        jLabel1.setText("________________________________________________");

        jLabelHouse1.setText("House Code :");

        jcbHouseFLF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select House" }));
        jcbHouseFLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHouseFLFActionPerformed(evt);
            }
        });
        jcbHouseFLF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbHouseFLFKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpFemaleLayout = new javax.swing.GroupLayout(jpFemale);
        jpFemale.setLayout(jpFemaleLayout);
        jpFemaleLayout.setHorizontalGroup(
            jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFemaleLayout.createSequentialGroup()
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFemaleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFemaleLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFemaleLayout.createSequentialGroup()
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFemale1)
                                    .addComponent(jLabelFemale3)
                                    .addComponent(jLabelFemale4)
                                    .addComponent(jLabelFemale2))
                                .addGap(18, 18, 18)
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFLFDeadT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLFDeadAP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLFCullAP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpFemaleLayout.createSequentialGroup()
                                .addComponent(jLabelFemale7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFLFInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFemaleLayout.createSequentialGroup()
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFemale5)
                                    .addComponent(jLabelFemale6))
                                .addGap(18, 18, 18)
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFLFDeadVac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLFCullT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpFemaleLayout.createSequentialGroup()
                        .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFemaleLayout.createSequentialGroup()
                                .addComponent(jLabelCode1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFemaleLayout.createSequentialGroup()
                                .addGap(0, 45, Short.MAX_VALUE)
                                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelHouse1)
                                    .addComponent(jLabelMO))
                                .addGap(9, 9, 9)))
                        .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpFemaleLayout.createSequentialGroup()
                                .addComponent(jTextMOFLF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSendMOFMF))
                            .addComponent(jcbHouseFLF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpFemaleLayout.setVerticalGroup(
            jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFemaleLayout.createSequentialGroup()
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFemaleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextMOFLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMO)
                            .addComponent(jButtonSendMOFMF)))
                    .addComponent(jLabelCode1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHouse1)
                    .addComponent(jcbHouseFLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale1))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFDeadAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale2))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFCullAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale3))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFDeadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale4))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFCullT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale5))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFDeadVac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale6))
                .addGap(18, 18, 18)
                .addGroup(jpFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLFInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFemale1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFLMDeadAP.setText("0");
        jTextFLMDeadAP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMDeadAPFocusLost(evt);
            }
        });

        jTextFLMCullAP.setText("0");
        jTextFLMCullAP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMCullAPFocusLost(evt);
            }
        });

        jTextFLMDeadT.setText("0");
        jTextFLMDeadT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMDeadTFocusLost(evt);
            }
        });

        jTextFLMCullT.setText("0");
        jTextFLMCullT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMCullTFocusLost(evt);
            }
        });

        jLabelFemale8.setText("ทั้งหมด :");

        jLabelFemale9.setText("ตายจากต้นทาง :");

        jLabelFemale10.setText("พิการจากต้นทาง :");

        jLabelFemale11.setText("ตายระหว่างขนส่ง :");

        jLabelFemale12.setText("พิการระหว่างขนส่ง :");

        jLabelFemale13.setText("ตายระหว่างวัคซีน :");

        jLabelFemale14.setText("ส่งเข้าฟาร์ม :");

        jTextFLMInsert.setText("0");
        jTextFLMInsert.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMInsertFocusLost(evt);
            }
        });

        jTextFLMDeadVac.setText("0");
        jTextFLMDeadVac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMDeadVacFocusLost(evt);
            }
        });

        jTextFLMTotal.setText("0");
        jTextFLMTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFLMTotalFocusLost(evt);
            }
        });

        jLabelCode3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCode3.setForeground(java.awt.Color.red);
        jLabelCode3.setText("Male");

        jLabel2.setText("________________________________________________");

        javax.swing.GroupLayout jpFemale1Layout = new javax.swing.GroupLayout(jpFemale1);
        jpFemale1.setLayout(jpFemale1Layout);
        jpFemale1Layout.setHorizontalGroup(
            jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFemale1Layout.createSequentialGroup()
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFemale1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFemale1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFemale1Layout.createSequentialGroup()
                                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFemale8)
                                    .addComponent(jLabelFemale10)
                                    .addComponent(jLabelFemale11)
                                    .addComponent(jLabelFemale9))
                                .addGap(18, 18, 18)
                                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFLMDeadT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLMDeadAP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLMCullAP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpFemale1Layout.createSequentialGroup()
                                .addComponent(jLabelFemale14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFLMInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFemale1Layout.createSequentialGroup()
                                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFemale12)
                                    .addComponent(jLabelFemale13))
                                .addGap(18, 18, 18)
                                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFLMDeadVac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFLMCullT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabelCode3))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jpFemale1Layout.setVerticalGroup(
            jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFemale1Layout.createSequentialGroup()
                .addComponent(jLabelCode3)
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale8))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMDeadAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale9))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMCullAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale10))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMDeadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale11))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMCullT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale12))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMDeadVac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale13))
                .addGap(18, 18, 18)
                .addGroup(jpFemale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLMInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFemale14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFMLLayout = new javax.swing.GroupLayout(jPanelFML);
        jPanelFML.setLayout(jPanelFMLLayout);
        jPanelFMLLayout.setHorizontalGroup(
            jPanelFMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFMLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFemale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpFemale1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelFMLLayout.setVerticalGroup(
            jPanelFMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFMLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpFemale1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("PS Laying Moulting", null, jPanelFML, "");

        jcbFlight.setText("2.สนามบิน");
        jcbFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFlockSTDate)
                        .addGap(10, 10, 10)
                        .addComponent(jXDateReceivied, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbHatchery)
                        .addGap(8, 8, 8)
                        .addComponent(jcbFlight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelTransport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFarm)
                        .addGap(10, 10, 10)
                        .addComponent(jcbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFlock)
                        .addGap(8, 8, 8)
                        .addComponent(jcbFlock, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFlockSTDate)
                    .addComponent(jXDateReceivied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStart)
                    .addComponent(jcbHatchery)
                    .addComponent(jTextFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFlight))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFarm)
                    .addComponent(jcbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHouse)
                    .addComponent(jcbHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFlock)
                    .addComponent(jcbFlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTransport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SumTotalFLF() {

        if ("".equals(jTextFLFTotal.getText())) {
            FLFTotal = 0;
        } else {
            FLFTotal = Integer.valueOf(jTextFLFTotal.getText());
        }

        if ("".equals(jTextFLFDeadAP.getText())) {
            FLFDeadAP = 0;
        } else {
            FLFDeadAP = Integer.valueOf(jTextFLFDeadAP.getText());
        }

        if ("".equals(jTextFLFCullAP.getText())) {
            FLFCullAP = 0;
        } else {
            FLFCullAP = Integer.valueOf(jTextFLFCullAP.getText());
        }

        if ("".equals(jTextFLFDeadT.getText())) {
            FLFDeadT = 0;
        } else {
            FLFDeadT = Integer.valueOf(jTextFLFDeadT.getText());
        }

        if ("".equals(jTextFLFCullT.getText())) {
            FLFCullT = 0;
        } else {
            FLFCullT = Integer.valueOf(jTextFLFCullT.getText());
        }

        if ("".equals(jTextFLFDeadVac.getText())) {
            FLFDeadVac = 0;
        } else {
            FLFDeadVac = Integer.valueOf(jTextFLFDeadVac.getText());
        }

        FLFSumTotal = FLFTotal - (FLFDeadAP + FLFCullAP + FLFDeadT + FLFCullT + FLFDeadVac);
        jTextFLFInsert.setText(String.valueOf(FLFSumTotal));
    }

    private void SumTotalFLM() {

        if ("".equals(jTextFLMTotal.getText())) {
            FLMTotal = 0;
        } else {
            FLMTotal = Integer.valueOf(jTextFLMTotal.getText());
        }

        if ("".equals(jTextFLMDeadAP.getText())) {
            FLMDeadAP = 0;
        } else {
            FLMDeadAP = Integer.valueOf(jTextFLMDeadAP.getText());
        }

        if ("".equals(jTextFLMCullAP.getText())) {
            FLMCullAP = 0;
        } else {
            FLMCullAP = Integer.valueOf(jTextFLMCullAP.getText());
        }

        if ("".equals(jTextFLMDeadT.getText())) {
            FLMDeadT = 0;
        } else {
            FLMDeadT = Integer.valueOf(jTextFLMDeadT.getText());
        }

        if ("".equals(jTextFLMCullT.getText())) {
            FLMCullT = 0;
        } else {
            FLMCullT = Integer.valueOf(jTextFLMCullT.getText());
        }

        if ("".equals(jTextFLMDeadVac.getText())) {
            FLMDeadVac = 0;
        } else {
            FLMDeadVac = Integer.valueOf(jTextFLMDeadVac.getText());
        }

        FLMSumTotal = FLMTotal - (FLMDeadAP + FLMCullAP + FLMDeadT + FLMCullT + FLMDeadVac);
        jTextFLMInsert.setText(String.valueOf(FLMSumTotal));
    }

    private void InsertDuck() {

        String[] getFarm = jcbFarm.getSelectedItem().toString().split(":");
        String vFarm = getFarm[0].trim();
        String[] getHouseFLF = jcbHouseFLF.getSelectedItem().toString().split(":");
        String vHouseFLF = getHouseFLF[0].trim();
        String[] getFlock = jcbFlock.getSelectedItem().toString().split(":");
        String vFlock = getFlock[0].trim();

        if ("FML".equals(JPanel)) {

            if ("Please Select : House".equals(jcbHouseFLF.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(null, "Please Select House");
                jcbHouseFLF.requestFocusInWindow();
            } else {

                // Insert Female Line
                FLFTotal = Integer.valueOf(jTextFLFTotal.getText());
                FLFDeadAP = Integer.valueOf(jTextFLFDeadAP.getText());
                FLFCullAP = Integer.valueOf(jTextFLFCullAP.getText());
                FLFDeadT = Integer.valueOf(jTextFLFDeadT.getText());
                FLFCullT = Integer.valueOf(jTextFLFCullT.getText());
                FLFDeadVac = Integer.valueOf(jTextFLFDeadVac.getText());
                FLFSumTotal = Integer.valueOf(jTextFLFInsert.getText());
                FLMTotal = Integer.valueOf(jTextFLMTotal.getText());
                FLMDeadAP = Integer.valueOf(jTextFLMDeadAP.getText());
                FLMCullAP = Integer.valueOf(jTextFLMCullAP.getText());
                FLMDeadT = Integer.valueOf(jTextFLMDeadT.getText());
                FLMCullT = Integer.valueOf(jTextFLMCullT.getText());
                FLMDeadVac = Integer.valueOf(jTextFLMDeadVac.getText());
                FLMSumTotal = Integer.valueOf(jTextFLMInsert.getText());
                String vCountFLF = crd.CheckLayingMTDuplicate(vFarm, vHouseFLF, sdf.format(jXDateReceivied.getDate()), BRLogin.vDuckBreed);

                if (Integer.valueOf(vCountFLF) > 0) {
                    JOptionPane.showMessageDialog(null, sdf.format(jXDateReceivied.getDate()) + " " + vHouseFLF + " Data Already");
                    StsTransferDuck = "No";
                } else {

                    cid.InsertMOLayingMT(vFarm, vHouseFLF, vFlock, sdf.format(jXDateReceivied.getDate()), jTextFlight.getText(), vFrom, jTextCar1.getText(), stf.format(jsST1.getValue()), stf.format(jsAR1.getValue()), jTextTem1.getText(), jTextCar2.getText(), stf.format(jsST2.getValue()), stf.format(jsAR2.getValue()), jTextTem2.getText(),
                            String.valueOf(FLFTotal), String.valueOf(FLMTotal), String.valueOf(FLFDeadAP), String.valueOf(FLMDeadAP), String.valueOf(FLFCullAP), String.valueOf(FLMCullAP), String.valueOf(FLFDeadT), String.valueOf(FLMDeadT), String.valueOf(FLFCullT), String.valueOf(FLMCullT), String.valueOf(FLFDeadVac), String.valueOf(FLMDeadVac), String.valueOf(FLFSumTotal), String.valueOf(FLMSumTotal), jTextMOFLF.getText(), BRLogin.vDuckBreed);
                    StsInsertDuck = "Yes";
                }
            }

        } 

    }

    private void TransferDuck() {

        String[] getFarm = jcbFarm.getSelectedItem().toString().split(":");
        String vFarm = getFarm[0].trim();
        String[] getHouseFLF = jcbHouseFLF.getSelectedItem().toString().split(":");
        String vHouseFLF = getHouseFLF[0].trim();
        String[] getFlock = jcbFlock.getSelectedItem().toString().split(":");
        String vFlock = getFlock[0].trim();
        String ItemFLF = "PS201004";
        String ItemFLM = "PS201006";

        if ("FML".equals(JPanel)) {

            String vCountInvenBal = crd.CheckInvenBalDuplicate(vFarm, vHouseFLF, sdf.format(jXDateReceivied.getDate()), ItemFLF, ItemFLM, BRLogin.vDuckBreed);
            String vCountInvenLot = crd.CheckInvenBalDuplicate(vFarm, vHouseFLF, sdf.format(jXDateReceivied.getDate()), ItemFLF, ItemFLM, BRLogin.vDuckBreed);
            String CheckInvenBalNotDateFLF = crd.CheckInvenBalDuplicateNotDate(BRLogin.vFarm, vHouseFLF, ItemFLF, ItemFLF, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll);
            String CheckInvenBalNotDateFLM = crd.CheckInvenBalDuplicateNotDate(BRLogin.vFarm, vHouseFLF, ItemFLM, ItemFLM, BRLogin.vDuckBreed, BRLogin.vDuckBreedAll);

            if (Integer.valueOf(vCountInvenBal) > 0) {
                JOptionPane.showMessageDialog(null, "Data Bal Post Already");
                StsTransferDuck = "No";
            } else if (Integer.valueOf(vCountInvenLot) > 0) {
                JOptionPane.showMessageDialog(null, "Data Lot Post Already");
                StsTransferDuck = "No";
            } else {

                //Insert InvenBal Female Line          
                if (Integer.valueOf(jTextFLFInsert.getText()) > 0) {

                    if (Integer.valueOf(CheckInvenBalNotDateFLF) == 0) {
                        cid.InsertInvenBal(vFarm, vHouseFLF, sdf.format(jXDateReceivied.getDate()), ItemFLF, jTextFLFInsert.getText(), BRLogin.vDuckBreed);
                    } else {
                        cid.UpdateInvenBalChangeDate(BRLogin.vFarm, vHouseFLF, sdf.format(jXDateReceivied.getDate()), ItemFLF, jTextFLFInsert.getText(), BRLogin.vDuckBreed, BRLogin.vDuckBreedAll);
                    }

                    cid.InsertInvenLot(vFarm, vHouseFLF, vFlock, sdf.format(jXDateReceivied.getDate()), ItemFLF, jTextFLFInsert.getText(), BRLogin.vDuckBreed);
                    cid.InsertMTransection(BRLogin.vFarm, sdf.format(jXDateReceivied.getDate()), vHouseFLF, ItemFLF, vFlock, "REC", BRLogin.vFarm, jTextFLFInsert.getText(), BRLogin.vDuckBreed);
                    cid.InsertDInvenBal(BRLogin.vFarm, vHouseFLF, sdf.format(jXDateReceivied.getDate()), ItemFLF, jTextFLFInsert.getText(), BRLogin.vDuckBreed);
                    cid.InsertDInvenLot(BRLogin.vFarm, vHouseFLF, vFlock, sdf.format(jXDateReceivied.getDate()), ItemFLF, jTextFLFInsert.getText(), BRLogin.vDuckBreed);
                }
                //Insert InvenBal Male Line   
                if (Integer.valueOf(jTextFLMInsert.getText()) > 0) {

                    if (Integer.valueOf(CheckInvenBalNotDateFLM) == 0) {
                        cid.InsertInvenBal(vFarm, vHouseFLF, sdf.format(jXDateReceivied.getDate()), ItemFLM, jTextFLMInsert.getText(), BRLogin.vDuckBreed);
                    } else {
                        cid.UpdateInvenBalChangeDate(BRLogin.vFarm, vHouseFLF, sdf.format(jXDateReceivied.getDate()), ItemFLM, jTextFLMInsert.getText(), BRLogin.vDuckBreed, BRLogin.vDuckBreedAll);
                    }

                    cid.InsertInvenLot(vFarm, vHouseFLF, vFlock, sdf.format(jXDateReceivied.getDate()), ItemFLM, jTextFLMInsert.getText(), BRLogin.vDuckBreed);
                    cid.InsertMTransection(BRLogin.vFarm, sdf.format(jXDateReceivied.getDate()), vHouseFLF, ItemFLM, vFlock, "REC", BRLogin.vFarm, jTextFLMInsert.getText(), BRLogin.vDuckBreed);
                    cid.InsertDInvenBal(BRLogin.vFarm, vHouseFLF, sdf.format(jXDateReceivied.getDate()), ItemFLM, jTextFLMInsert.getText(), BRLogin.vDuckBreed);
                    cid.InsertDInvenLot(BRLogin.vFarm, vHouseFLF, vFlock, sdf.format(jXDateReceivied.getDate()), ItemFLM, jTextFLMInsert.getText(), BRLogin.vDuckBreed);
                }
                StsTransferDuck = "Yes";
            }

        } 

    }

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here: 

        try {

            if ("".equals(jTextFLFInsert.getText())) {
                JOptionPane.showMessageDialog(null, "Please Insert Qty");
                jTextFLFInsert.requestFocusInWindow();
            } else if ("".equals(jTextFLMInsert.getText())) {
                JOptionPane.showMessageDialog(null, "Please Insert Qty");
                jTextFLFInsert.requestFocusInWindow();
            } else if ("Please Select : Farm".equals(jcbFarm.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(null, "Please Select Farm");
                jcbFarm.requestFocusInWindow();
            } else if ("Please Select : Flock".equals(jcbFlock.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(null, "Please Select Flock");
                jcbFlock.requestFocusInWindow();
            } else {
                InsertDuck();
                if ("Yes".equals(StsInsertDuck)) {
                    TransferDuck();
                }

                if ("Yes".equals(StsInsertDuck) && "Yes".equals(StsTransferDuck)) {
                    JOptionPane.showMessageDialog(null, "Data Post Completed");
                    StsInsertDuck = "No";
                    StsTransferDuck = "No";
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jcbFarmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbFarmKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFarmKeyPressed

    private void jTextMOFLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMOFLFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMOFLFActionPerformed

    private void jTextFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFlightActionPerformed

    private void jButtonSendMOFMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSendMOFMFMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSendMOFMFMouseClicked

    private void jButtonSendMOFMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendMOFMFActionPerformed
        // TODO add your handling code here:

        try {

            if ("".equals(jTextMOFLF.getText())) {
                JOptionPane.showMessageDialog(null, "Please Insert MO");
            } else if ("Please Select : House".equals(jcbHouseFLF.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(null, "Please Select House");
            } else {

                String[] getFarm = jcbFarm.getSelectedItem().toString().split(":");
                String vFarm = getFarm[0].trim();
                String[] getHouse = jcbHouseFLF.getSelectedItem().toString().split(":");
                String vHouse = getHouse[0].trim();

                cid.UpdateMOGrower(vFarm, vHouse, jTextMOFLF.getText());
                JOptionPane.showMessageDialog(null, "Sending MO-Grower Duck is Completed");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_jButtonSendMOFMFActionPerformed

    private void jTextCar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCar1ActionPerformed

    private void jTextCar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCar2ActionPerformed

    private void jTextTem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTem1ActionPerformed

    private void jTextTem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTem2ActionPerformed

    private void jcbFlockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbFlockKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFlockKeyPressed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jTextFLFDeadAPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFDeadAPFocusLost
        // TODO add your handling code here:
        SumTotalFLF();
    }//GEN-LAST:event_jTextFLFDeadAPFocusLost

    private void jTextFLFCullAPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFCullAPFocusLost
        // TODO add your handling code here:
        SumTotalFLF();
    }//GEN-LAST:event_jTextFLFCullAPFocusLost

    private void jTextFLFDeadTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFDeadTFocusLost
        // TODO add your handling code here:
        SumTotalFLF();
    }//GEN-LAST:event_jTextFLFDeadTFocusLost

    private void jTextFLFCullTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFCullTFocusLost
        // TODO add your handling code here:
        SumTotalFLF();
    }//GEN-LAST:event_jTextFLFCullTFocusLost

    private void jTextFLFDeadVacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFDeadVacFocusLost
        // TODO add your handling code here:
        SumTotalFLF();
    }//GEN-LAST:event_jTextFLFDeadVacFocusLost

    private void jTextFLFInsertFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFInsertFocusLost
        // TODO add your handling code here:
        SumTotalFLF();
    }//GEN-LAST:event_jTextFLFInsertFocusLost

    private void jTextFLFTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLFTotalFocusLost
        // TODO add your handling code here:
        SumTotalFLF();
    }//GEN-LAST:event_jTextFLFTotalFocusLost

    private void jTextFLMTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMTotalFocusLost
        // TODO add your handling code here:
        SumTotalFLM();
    }//GEN-LAST:event_jTextFLMTotalFocusLost

    private void jTextFLMDeadAPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMDeadAPFocusLost
        // TODO add your handling code here:
        SumTotalFLM();
    }//GEN-LAST:event_jTextFLMDeadAPFocusLost

    private void jTextFLMCullAPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMCullAPFocusLost
        // TODO add your handling code here:
        SumTotalFLM();
    }//GEN-LAST:event_jTextFLMCullAPFocusLost

    private void jTextFLMDeadTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMDeadTFocusLost
        // TODO add your handling code here:
        SumTotalFLM();
    }//GEN-LAST:event_jTextFLMDeadTFocusLost

    private void jTextFLMCullTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMCullTFocusLost
        // TODO add your handling code here:
        SumTotalFLM();
    }//GEN-LAST:event_jTextFLMCullTFocusLost

    private void jTextFLMDeadVacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMDeadVacFocusLost
        // TODO add your handling code here:
        SumTotalFLM();
    }//GEN-LAST:event_jTextFLMDeadVacFocusLost

    private void jTextFLMInsertFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFLMInsertFocusLost
        // TODO add your handling code here:
        SumTotalFLM();
    }//GEN-LAST:event_jTextFLMInsertFocusLost

    private void jPanelFMLComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelFMLComponentShown
        // TODO add your handling code here:
        JPanel = "FML";
    }//GEN-LAST:event_jPanelFMLComponentShown

    private void jcbHouseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbHouseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHouseKeyPressed

    private void jcbHouseFLFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbHouseFLFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHouseFLFKeyPressed

    private void jcbHatcheryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHatcheryActionPerformed
        // TODO add your handling code here:
        if (jcbHatchery.isSelected() == true) {
            vFrom = "1";
            jcbFlight.setSelected(false);
            jTextFlight.setEnabled(false);
            jTextFlight.setText("");
        } else {
            vFrom = null;
        }
    }//GEN-LAST:event_jcbHatcheryActionPerformed

    private void jcbFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFlightActionPerformed
        // TODO add your handling code here:
        if (jcbFlight.isSelected() == true) {
            vFrom = "2";
            jcbHatchery.setSelected(false);
            jTextFlight.setEnabled(true);
        } else {
            vFrom = null;
            jTextFlight.setEnabled(false);
            jTextFlight.setText("");
        }
    }//GEN-LAST:event_jcbFlightActionPerformed

    private void jcbHouseFLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHouseFLFActionPerformed
        // TODO add your handling code here:
        String[] getHouseFLF = jcbHouseFLF.getSelectedItem().toString().split(":");
        String vHouseFLF = getHouseFLF[0].trim();
        jTextMOFLF.setText(crd.CheckLastMO(BRLogin.vFarm, BRLogin.vDuckBreed, vHouseFLF));
        jTextMOFLF.setForeground(Color.blue);
    }//GEN-LAST:event_jcbHouseFLFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BRPS05LMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BRPS05LMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BRPS05LMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BRPS05LMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BRPS05LMT().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSendMOFMF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAR1;
    private javax.swing.JLabel jLabelAR2;
    private javax.swing.JLabel jLabelCar1;
    private javax.swing.JLabel jLabelCar2;
    private javax.swing.JLabel jLabelCode1;
    private javax.swing.JLabel jLabelCode2;
    private javax.swing.JLabel jLabelCode3;
    private javax.swing.JLabel jLabelFarm;
    private javax.swing.JLabel jLabelFemale1;
    private javax.swing.JLabel jLabelFemale10;
    private javax.swing.JLabel jLabelFemale11;
    private javax.swing.JLabel jLabelFemale12;
    private javax.swing.JLabel jLabelFemale13;
    private javax.swing.JLabel jLabelFemale14;
    private javax.swing.JLabel jLabelFemale2;
    private javax.swing.JLabel jLabelFemale3;
    private javax.swing.JLabel jLabelFemale4;
    private javax.swing.JLabel jLabelFemale5;
    private javax.swing.JLabel jLabelFemale6;
    private javax.swing.JLabel jLabelFemale7;
    private javax.swing.JLabel jLabelFemale8;
    private javax.swing.JLabel jLabelFemale9;
    private javax.swing.JLabel jLabelFlock;
    private javax.swing.JLabel jLabelFlockSTDate;
    private javax.swing.JLabel jLabelHouse;
    private javax.swing.JLabel jLabelHouse1;
    private javax.swing.JLabel jLabelMO;
    private javax.swing.JLabel jLabelST1;
    private javax.swing.JLabel jLabelST2;
    private javax.swing.JLabel jLabelStart;
    private javax.swing.JLabel jLabelTem1;
    private javax.swing.JLabel jLabelTem2;
    private javax.swing.JPanel jPanelFML;
    private javax.swing.JPanel jPanelTransport;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextCar1;
    private javax.swing.JTextField jTextCar2;
    private javax.swing.JTextField jTextFLFCullAP;
    private javax.swing.JTextField jTextFLFCullT;
    private javax.swing.JTextField jTextFLFDeadAP;
    private javax.swing.JTextField jTextFLFDeadT;
    private javax.swing.JTextField jTextFLFDeadVac;
    private javax.swing.JTextField jTextFLFInsert;
    private javax.swing.JTextField jTextFLFTotal;
    private javax.swing.JTextField jTextFLMCullAP;
    private javax.swing.JTextField jTextFLMCullT;
    private javax.swing.JTextField jTextFLMDeadAP;
    private javax.swing.JTextField jTextFLMDeadT;
    private javax.swing.JTextField jTextFLMDeadVac;
    private javax.swing.JTextField jTextFLMInsert;
    private javax.swing.JTextField jTextFLMTotal;
    private javax.swing.JTextField jTextFlight;
    private javax.swing.JTextField jTextMOFLF;
    private javax.swing.JTextField jTextTem1;
    private javax.swing.JTextField jTextTem2;
    private org.jdesktop.swingx.JXDatePicker jXDateReceivied;
    private javax.swing.JComboBox jcbFarm;
    private javax.swing.JCheckBox jcbFlight;
    private javax.swing.JComboBox jcbFlock;
    private javax.swing.JCheckBox jcbHatchery;
    private javax.swing.JComboBox jcbHouse;
    private javax.swing.JComboBox jcbHouseFLF;
    private javax.swing.JPanel jpFemale;
    private javax.swing.JPanel jpFemale1;
    private javax.swing.JSpinner jsAR1;
    private javax.swing.JSpinner jsAR2;
    private javax.swing.JSpinner jsST1;
    private javax.swing.JSpinner jsST2;
    // End of variables declaration//GEN-END:variables

}
